#!/usr/bin/env bash
# Fail if any tracked source file contains a TODO that isn't tagged with a GitHub issue URL.
#
# Allowed form (case-sensitive on "TODO"):
#   TODO(<https://github.com/<owner>/<repo>/issues/<N>>): ...
#
# The angle-bracketed URL form is required everywhere — bare `TODO(https://...)` fails
# rustdoc's `bare-urls` lint inside `///` doc comments, so we mandate the safe form in
# every comment for uniformity. Bare `#NNNN` is also rejected so editors render the link.
#
# Excluded paths (third-party / generated / docs):
#   runtimes/next-asset-hub-paseo/   — synced from polkadot-fellows/runtimes
#   paseo-support/                   — synced from upstream Substrate
#   **/weights/                      — generated by frame-omni-bencher
#   .github/scripts/check_todos.sh   — self-reference
#
# Run locally:
#   .github/scripts/check_todos.sh

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

# A `TODO` is OK only if immediately followed by `(<https://...>)`.
PATTERN='\bTODO\b(?!\(<https://[^>)\s]+>\))'

# Tracked text files, minus exclusions.
files=$(
	git ls-files '*.rs' '*.toml' '*.yml' '*.yaml' '*.sh' '*.md' \
		| grep -Ev '^(runtimes/next-asset-hub-paseo/|paseo-support/)' \
		| grep -Ev '/weights/' \
		| grep -Ev '^\.github/scripts/check_todos\.sh$' \
		|| true
)

if [[ -z "$files" ]]; then
	echo "no files to scan"
	exit 0
fi

# Pick a PCRE-capable scanner. ripgrep is preferred; GNU grep -P is the fallback.
if command -v rg >/dev/null 2>&1; then
	offenders=$(printf '%s\n' "$files" | xargs rg -n --no-heading -P "$PATTERN" || true)
elif command grep --version 2>/dev/null | grep -q "GNU grep"; then
	offenders=$(printf '%s\n' "$files" | xargs command grep -nHP "$PATTERN" || true)
else
	echo "need ripgrep or GNU grep" >&2
	exit 2
fi

if [[ -n "$offenders" ]]; then
	echo "Found TODO without a bracketed GitHub issue URL (expected \`TODO(<https://github.com/.../issues/NNNN>):\`):" >&2
	echo "$offenders" >&2
	echo >&2
	echo "Tag each TODO with the full issue URL in angle brackets" >&2
	echo "Brackets are required so rustdoc's \`bare-urls\` lint accepts the form inside \`///\` comments." >&2
	echo "If the file is third-party/generated and should be skipped, add its path to" >&2
	echo "the exclusion list in .github/scripts/check_todos.sh." >&2
	exit 1
fi

echo "all TODOs have a GitHub issue URL"
