// Copyright (C) Parity Technologies (UK) Ltd.
// This file is part of Individuality.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `indiv_pallet_resources`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 60.0.0
//! DATE: 2026-10-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `parity-weights-2b499ea167c64aa7`, CPU: `Intel(R) Xeon(R) CPU @ 2.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --extrinsic=*
// --runtime=target/production/wbuild/next-people-paseo-runtime/next_people_paseo_runtime.wasm
// --pallet=indiv_pallet_resources
// --header=/home/runner/actions-runner/_work/individuality-community/individuality-community/.github/scripts/cmd/file_header.txt
// --output=./runtimes/next-people-paseo/src/weights
// --wasm-execution=compiled
// --steps=50
// --repeat=20
// --min-duration=1
// --heap-pages=4096
// --genesis-builder=runtime
// --no-storage-info
// --no-min-squares
// --no-median-slopes

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `indiv_pallet_resources`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> indiv_pallet_resources::WeightInfo for WeightInfo<T> {
	/// Storage: `Resources::Consumers` (r:1 w:1)
	/// Proof: `Resources::Consumers` (`max_values`: None, `max_size`: Some(155), added: 2630, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:1 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a22e18c5ed5846cada3ffa7` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a22e18c5ed5846cada3ffa7` (r:1 w:1)
	fn register_lite_person() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3620`
		// Minimum execution time: 20_451_000 picoseconds.
		Weight::from_parts(21_971_000, 0)
			.saturating_add(Weight::from_parts(0, 3620))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `NetworkSuffix::NetworkSuffix` (r:1 w:0)
	/// Proof: `NetworkSuffix::NetworkSuffix` (`max_values`: Some(1), `max_size`: Some(17), added: 512, mode: `MaxEncodedLen`)
	/// Storage: `Resources::AccountOfAlias` (r:1 w:1)
	/// Proof: `Resources::AccountOfAlias` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Resources::Consumers` (r:1 w:1)
	/// Proof: `Resources::Consumers` (`max_values`: None, `max_size`: Some(155), added: 2630, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:2 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a8a88e3dd7409f195fd52db` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a8a88e3dd7409f195fd52db` (r:1 w:1)
	fn register_person() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `295`
		//  Estimated: `6044`
		// Minimum execution time: 77_988_000 picoseconds.
		Weight::from_parts(84_908_000, 0)
			.saturating_add(Weight::from_parts(0, 6044))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `NetworkSuffix::NetworkSuffix` (r:1 w:0)
	/// Proof: `NetworkSuffix::NetworkSuffix` (`max_values`: Some(1), `max_size`: Some(17), added: 512, mode: `MaxEncodedLen`)
	/// Storage: `Resources::AccountOfAlias` (r:1 w:0)
	/// Proof: `Resources::AccountOfAlias` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Resources::Consumers` (r:1 w:1)
	/// Proof: `Resources::Consumers` (`max_values`: None, `max_size`: Some(155), added: 2630, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:2 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a8a88e3dd7409f195fd52db` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a8a88e3dd7409f195fd52db` (r:1 w:1)
	fn touch_person_authorization() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `441`
		//  Estimated: `6044`
		// Minimum execution time: 36_477_000 picoseconds.
		Weight::from_parts(39_953_000, 0)
			.saturating_add(Weight::from_parts(0, 6044))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Resources::Consumers` (r:1 w:1)
	/// Proof: `Resources::Consumers` (`max_values`: None, `max_size`: Some(155), added: 2630, mode: `MaxEncodedLen`)
	fn update_identifier_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `187`
		//  Estimated: `3620`
		// Minimum execution time: 12_705_000 picoseconds.
		Weight::from_parts(13_742_000, 0)
			.saturating_add(Weight::from_parts(0, 3620))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Resources::Consumers` (r:1 w:1)
	/// Proof: `Resources::Consumers` (`max_values`: None, `max_size`: Some(155), added: 2630, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:2 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ad861ea1ebf4800d4b89f4f` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ad861ea1ebf4800d4b89f4f` (r:1 w:1)
	fn demote_auth_expired() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `264`
		//  Estimated: `6044`
		// Minimum execution time: 25_693_000 picoseconds.
		Weight::from_parts(27_719_000, 0)
			.saturating_add(Weight::from_parts(0, 6044))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Resources::Consumers` (r:1 w:0)
	/// Proof: `Resources::Consumers` (`max_values`: None, `max_size`: Some(155), added: 2630, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn authorize_demote_auth_expired() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `261`
		//  Estimated: `3620`
		// Minimum execution time: 9_318_000 picoseconds.
		Weight::from_parts(10_143_000, 0)
			.saturating_add(Weight::from_parts(0, 3620))
			.saturating_add(T::DbWeight::get().reads(2))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:3 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Resources::NotificationRegistrationByAlias` (r:1 w:1)
	/// Proof: `Resources::NotificationRegistrationByAlias` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `Resources::NotificationAliasByAccount` (r:1 w:1)
	/// Proof: `Resources::NotificationAliasByAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ad861ea1ebf4800d4b89f4f` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ad861ea1ebf4800d4b89f4f` (r:1 w:1)
	fn set_notification_statement_account_for_sequence() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `80`
		//  Estimated: `8571`
		// Minimum execution time: 27_192_000 picoseconds.
		Weight::from_parts(29_237_000, 0)
			.saturating_add(Weight::from_parts(0, 8571))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Resources::NotificationAliasByAccount` (r:1 w:1)
	/// Proof: `Resources::NotificationAliasByAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:1 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ad861ea1ebf4800d4b89f4f` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ad861ea1ebf4800d4b89f4f` (r:1 w:1)
	/// Storage: `Resources::NotificationRegistrationByAlias` (r:0 w:1)
	/// Proof: `Resources::NotificationRegistrationByAlias` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn clear_expired_notification_sequence() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `146`
		//  Estimated: `3611`
		// Minimum execution time: 19_083_000 picoseconds.
		Weight::from_parts(20_440_000, 0)
			.saturating_add(Weight::from_parts(0, 3611))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Resources::NotificationAliasByAccount` (r:1 w:0)
	/// Proof: `Resources::NotificationAliasByAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Resources::NotificationRegistrationByAlias` (r:1 w:0)
	/// Proof: `Resources::NotificationRegistrationByAlias` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:2 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn authorize_clear_expired_notification_sequence() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `295`
		//  Estimated: `6044`
		// Minimum execution time: 19_807_000 picoseconds.
		Weight::from_parts(21_062_000, 0)
			.saturating_add(Weight::from_parts(0, 6044))
			.saturating_add(T::DbWeight::get().reads(5))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:2 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NetworkSuffix::NetworkSuffix` (r:1 w:0)
	/// Proof: `NetworkSuffix::NetworkSuffix` (`max_values`: Some(1), `max_size`: Some(17), added: 512, mode: `MaxEncodedLen`)
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::Root` (r:1 w:0)
	/// Proof: `Members::Root` (`max_values`: None, `max_size`: Some(1192), added: 3667, mode: `MaxEncodedLen`)
	/// Storage: `Resources::NotificationRegistrationByAlias` (r:1 w:0)
	/// Proof: `Resources::NotificationRegistrationByAlias` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `Resources::NotificationAliasByAccount` (r:1 w:0)
	/// Proof: `Resources::NotificationAliasByAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn as_register_with_proof_tx_ext() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1719`
		//  Estimated: `6044`
		// Minimum execution time: 28_801_207_000 picoseconds.
		Weight::from_parts(29_125_184_000, 0)
			.saturating_add(Weight::from_parts(0, 6044))
			.saturating_add(T::DbWeight::get().reads(8))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:3 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NetworkSuffix::NetworkSuffix` (r:1 w:0)
	/// Proof: `NetworkSuffix::NetworkSuffix` (`max_values`: Some(1), `max_size`: Some(17), added: 512, mode: `MaxEncodedLen`)
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::Root` (r:1 w:0)
	/// Proof: `Members::Root` (`max_values`: None, `max_size`: Some(1192), added: 3667, mode: `MaxEncodedLen`)
	/// Storage: `Resources::NotificationRegistrationByAlias` (r:1 w:0)
	/// Proof: `Resources::NotificationRegistrationByAlias` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `Resources::NotificationAliasByAccount` (r:1 w:0)
	/// Proof: `Resources::NotificationAliasByAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn as_register_for_collection_tx_ext() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1721`
		//  Estimated: `8571`
		// Minimum execution time: 28_979_738_000 picoseconds.
		Weight::from_parts(29_184_323_000, 0)
			.saturating_add(Weight::from_parts(0, 8571))
			.saturating_add(T::DbWeight::get().reads(9))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Resources::StatementStoreAllowances` (r:1 w:1)
	/// Proof: `Resources::StatementStoreAllowances` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:2 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a30ea23cebb6ae1aee09eec` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a30ea23cebb6ae1aee09eec` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ad861ea1ebf4800d4b89f4f` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ad861ea1ebf4800d4b89f4f` (r:1 w:1)
	/// Storage: `Resources::StmtStoreAllowanceByAccount` (r:0 w:2)
	/// Proof: `Resources::StmtStoreAllowanceByAccount` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn set_statement_store_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `238`
		//  Estimated: `6044`
		// Minimum execution time: 34_750_000 picoseconds.
		Weight::from_parts(36_568_000, 0)
			.saturating_add(Weight::from_parts(0, 6044))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `Parameters::Parameters` (r:2 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Resources::StatementStoreAllowances` (r:51 w:50)
	/// Proof: `Resources::StatementStoreAllowances` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ac63a1bf52b1a4480965cc7` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ac63a1bf52b1a4480965cc7` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ac0e7597415ab1a40d6c1f5` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ac0e7597415ab1a40d6c1f5` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653aa5df714461161c3682b298` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653aa5df714461161c3682b298` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a1d75512892a62807e2d778` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a1d75512892a62807e2d778` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a958c9c8ab2e26068fb09e5` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a958c9c8ab2e26068fb09e5` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653aec62566cb9604951079869` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653aec62566cb9604951079869` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653aa6c480ae4378bb56c95490` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653aa6c480ae4378bb56c95490` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a153c8e71dea15474e899e5` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a153c8e71dea15474e899e5` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a5c554888d2c266606057ca` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a5c554888d2c266606057ca` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a1928005fed04082b8f9946` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a1928005fed04082b8f9946` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a2917f88e5ca2cd501fcae3` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a2917f88e5ca2cd501fcae3` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a8eef2c854df21dd72f8c27` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a8eef2c854df21dd72f8c27` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653aaa93608dc7b51f8746401d` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653aaa93608dc7b51f8746401d` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a2547c8edf8e90b95c3c176` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a2547c8edf8e90b95c3c176` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ab16aff84dc0986b061bd4e` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ab16aff84dc0986b061bd4e` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a05fa90305ba0a4ba2011ab` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a05fa90305ba0a4ba2011ab` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653abd5f2181992dbea7e07fb2` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653abd5f2181992dbea7e07fb2` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ad0daa238471211deadfa31` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ad0daa238471211deadfa31` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653aa6f1d6ff8c5e7895b6db95` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653aa6f1d6ff8c5e7895b6db95` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a0c80fdd451e91054e932c9` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a0c80fdd451e91054e932c9` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a25fbb1a711c24895f7168f` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a25fbb1a711c24895f7168f` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653abc7b1dc43676bc9e74fccd` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653abc7b1dc43676bc9e74fccd` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a77b4a95551542731b3993b` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a77b4a95551542731b3993b` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ae6396f3b44427faf6448de` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ae6396f3b44427faf6448de` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653aa8a6055ba74b24507077a8` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653aa8a6055ba74b24507077a8` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ad8a39198c9ae4d4b943cf7` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ad8a39198c9ae4d4b943cf7` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653af2b9ad3262e2916b64da01` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653af2b9ad3262e2916b64da01` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a58072b72292c21af41031e` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a58072b72292c21af41031e` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a535dc0c215c9e2377671ae` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a535dc0c215c9e2377671ae` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a8d4a61b8675b052017a52e` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a8d4a61b8675b052017a52e` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a8bf68829f149272bfdb6ce` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a8bf68829f149272bfdb6ce` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ac9421230d848ddf3497dd3` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ac9421230d848ddf3497dd3` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a2fa651cd7d97cc5f1158af` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a2fa651cd7d97cc5f1158af` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a33cb76ce16adf23f2a09fe` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a33cb76ce16adf23f2a09fe` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a775560928194999d31915d` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a775560928194999d31915d` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a5fe2adfde97ff8d72865a0` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a5fe2adfde97ff8d72865a0` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a79f0cf88f93ed9b09f6f19` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a79f0cf88f93ed9b09f6f19` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a2470d7530c5cec5f494946` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a2470d7530c5cec5f494946` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a0672ec51a6380ceaa27e8c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a0672ec51a6380ceaa27e8c` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a281d8aa8d9bd7f21f1ed4c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a281d8aa8d9bd7f21f1ed4c` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a400870151cb706a0633eeb` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a400870151cb706a0633eeb` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a3ec974b94bc1640bf0745c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a3ec974b94bc1640bf0745c` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a9ce32ab3e7e62c13826259` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a9ce32ab3e7e62c13826259` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ae6e0c68313c22f44c1b3d1` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ae6e0c68313c22f44c1b3d1` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a31d568f065dae1f0f1ec8b` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a31d568f065dae1f0f1ec8b` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a2d5ea2c6cede16478d3c5a` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a2d5ea2c6cede16478d3c5a` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a644832a7622a9b309c096c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a644832a7622a9b309c096c` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653aa6d5bd953c89e4287b523c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653aa6d5bd953c89e4287b523c` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653af5fde8bf7e4acd613e7061` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653af5fde8bf7e4acd613e7061` (r:1 w:1)
	/// Storage: `Resources::StmtStoreAllowanceByAccount` (r:0 w:50)
	/// Proof: `Resources::StmtStoreAllowanceByAccount` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 50]`.
	fn clear_expired_stmt_store_allowances(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + n * (138 ±0)`
		//  Estimated: `6044 + n * (2571 ±0)`
		// Minimum execution time: 26_974_000 picoseconds.
		Weight::from_parts(15_184_907, 0)
			.saturating_add(Weight::from_parts(0, 6044))
			// Standard Error: 14_210
			.saturating_add(Weight::from_parts(13_239_040, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2571).saturating_mul(n.into()))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:1 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Resources::StatementStoreAllowances` (r:1 w:0)
	/// Proof: `Resources::StatementStoreAllowances` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	fn authorize_clear_expired_stmt_store_allowances() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `223`
		//  Estimated: `3561`
		// Minimum execution time: 10_018_000 picoseconds.
		Weight::from_parts(10_812_000, 0)
			.saturating_add(Weight::from_parts(0, 3561))
			.saturating_add(T::DbWeight::get().reads(3))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:3 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NetworkSuffix::NetworkSuffix` (r:1 w:0)
	/// Proof: `NetworkSuffix::NetworkSuffix` (`max_values`: Some(1), `max_size`: Some(17), added: 512, mode: `MaxEncodedLen`)
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::Root` (r:1 w:0)
	/// Proof: `Members::Root` (`max_values`: None, `max_size`: Some(1192), added: 3667, mode: `MaxEncodedLen`)
	/// Storage: `Resources::StatementStoreAllowances` (r:1 w:0)
	/// Proof: `Resources::StatementStoreAllowances` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	fn as_stmt_store_allowance_tx_ext() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1845`
		//  Estimated: `8571`
		// Minimum execution time: 28_969_875_000 picoseconds.
		Weight::from_parts(29_307_648_000, 0)
			.saturating_add(Weight::from_parts(0, 8571))
			.saturating_add(T::DbWeight::get().reads(8))
	}
	/// Storage: `Parameters::Parameters` (r:1 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Resources::SpentLongTermStorageAliases` (r:0 w:1)
	/// Proof: `Resources::SpentLongTermStorageAliases` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn claim_long_term_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3`
		//  Estimated: `3517`
		// Minimum execution time: 10_365_000 picoseconds.
		Weight::from_parts(11_136_000, 0)
			.saturating_add(Weight::from_parts(0, 3517))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:2 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NetworkSuffix::NetworkSuffix` (r:1 w:0)
	/// Proof: `NetworkSuffix::NetworkSuffix` (`max_values`: Some(1), `max_size`: Some(17), added: 512, mode: `MaxEncodedLen`)
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::Root` (r:1 w:0)
	/// Proof: `Members::Root` (`max_values`: None, `max_size`: Some(1192), added: 3667, mode: `MaxEncodedLen`)
	/// Storage: `Resources::SpentLongTermStorageAliases` (r:1 w:0)
	/// Proof: `Resources::SpentLongTermStorageAliases` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn claim_long_term_storage_tx_ext() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1721`
		//  Estimated: `6044`
		// Minimum execution time: 28_935_758_000 picoseconds.
		Weight::from_parts(29_193_054_000, 0)
			.saturating_add(Weight::from_parts(0, 6044))
			.saturating_add(T::DbWeight::get().reads(7))
	}
	/// Storage: `Parameters::Parameters` (r:1 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Resources::SpentLongTermStorageAliases` (r:21 w:20)
	/// Proof: `Resources::SpentLongTermStorageAliases` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 20]`.
	fn clear_expired_long_term_storage_aliases(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `33 + n * (53 ±0)`
		//  Estimated: `3517 + n * (2527 ±0)`
		// Minimum execution time: 16_442_000 picoseconds.
		Weight::from_parts(15_569_072, 0)
			.saturating_add(Weight::from_parts(0, 3517))
			// Standard Error: 13_702
			.saturating_add(Weight::from_parts(4_239_673, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2527).saturating_mul(n.into()))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:2 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Resources::SpentLongTermStorageAliases` (r:1 w:0)
	/// Proof: `Resources::SpentLongTermStorageAliases` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn authorize_clear_expired_long_term_storage_aliases() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `158`
		//  Estimated: `6044`
		// Minimum execution time: 14_017_000 picoseconds.
		Weight::from_parts(14_767_000, 0)
			.saturating_add(Weight::from_parts(0, 6044))
			.saturating_add(T::DbWeight::get().reads(4))
	}
	/// Storage: `Resources::Consumers` (r:2 w:1)
	/// Proof: `Resources::Consumers` (`max_values`: None, `max_size`: Some(155), added: 2630, mode: `MaxEncodedLen`)
	fn migrate_v1_translate_consumer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `254`
		//  Estimated: `6250`
		// Minimum execution time: 9_225_000 picoseconds.
		Weight::from_parts(10_068_000, 0)
			.saturating_add(Weight::from_parts(0, 6250))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: UNKNOWN KEY `0x2111e0df19de9563b58301e5f7e00743099c711e270af23bb9a4e46759a9761d` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x2111e0df19de9563b58301e5f7e00743099c711e270af23bb9a4e46759a9761d` (r:1 w:1)
	fn migrate_v1_clear_username_entry() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `110`
		//  Estimated: `3575`
		// Minimum execution time: 3_370_000 picoseconds.
		Weight::from_parts(3_700_000, 0)
			.saturating_add(Weight::from_parts(0, 3575))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
