// Copyright (C) Parity Technologies (UK) Ltd.
// This file is part of Individuality.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `indiv_pallet_people_lite`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 60.0.0
//! DATE: 2026-10-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `parity-weights-2b499ea167c64aa7`, CPU: `Intel(R) Xeon(R) CPU @ 2.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --extrinsic=*
// --runtime=target/production/wbuild/next-people-paseo-runtime/next_people_paseo_runtime.wasm
// --pallet=indiv_pallet_people_lite
// --header=/home/runner/actions-runner/_work/individuality-community/individuality-community/.github/scripts/cmd/file_header.txt
// --output=./runtimes/next-people-paseo/src/weights
// --wasm-execution=compiled
// --steps=50
// --repeat=20
// --min-duration=1
// --heap-pages=4096
// --genesis-builder=runtime
// --no-storage-info
// --no-min-squares
// --no-median-slopes

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `indiv_pallet_people_lite`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> indiv_pallet_people_lite::WeightInfo for WeightInfo<T> {
	/// Storage: `PeopleLite::LitePeople` (r:1 w:0)
	/// Proof: `PeopleLite::LitePeople` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	fn as_lite_person_tx_ext() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `128`
		//  Estimated: `3578`
		// Minimum execution time: 14_729_000 picoseconds.
		Weight::from_parts(16_094_000, 0)
			.saturating_add(Weight::from_parts(0, 3578))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `PeopleLite::AccountToAlias` (r:1 w:0)
	/// Proof: `PeopleLite::AccountToAlias` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Members::Root` (r:1 w:0)
	/// Proof: `Members::Root` (`max_values`: None, `max_size`: Some(1192), added: 3667, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn as_lite_alias_with_account_tx_ext() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1883`
		//  Estimated: `4657`
		// Minimum execution time: 42_824_000 picoseconds.
		Weight::from_parts(44_298_000, 0)
			.saturating_add(Weight::from_parts(0, 4657))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `NetworkSuffix::NetworkSuffix` (r:1 w:0)
	/// Proof: `NetworkSuffix::NetworkSuffix` (`max_values`: Some(1), `max_size`: Some(17), added: 512, mode: `MaxEncodedLen`)
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Members::Root` (r:1 w:0)
	/// Proof: `Members::Root` (`max_values`: None, `max_size`: Some(1192), added: 3667, mode: `MaxEncodedLen`)
	/// Storage: `PeopleLite::AccountToAlias` (r:1 w:0)
	/// Proof: `PeopleLite::AccountToAlias` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	fn as_lite_alias_with_proof_tx_ext() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1889`
		//  Estimated: `4657`
		// Minimum execution time: 28_878_071_000 picoseconds.
		Weight::from_parts(29_175_031_000, 0)
			.saturating_add(Weight::from_parts(0, 4657))
			.saturating_add(T::DbWeight::get().reads(5))
	}
	/// Storage: `PeopleLite::AccountToAlias` (r:1 w:1)
	/// Proof: `PeopleLite::AccountToAlias` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `NetworkSuffix::NetworkSuffix` (r:1 w:0)
	/// Proof: `NetworkSuffix::NetworkSuffix` (`max_values`: Some(1), `max_size`: Some(17), added: 512, mode: `MaxEncodedLen`)
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Members::Root` (r:1 w:0)
	/// Proof: `Members::Root` (`max_values`: None, `max_size`: Some(1192), added: 3667, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn as_lite_alias_with_account_revised_tx_ext() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2063`
		//  Estimated: `4657`
		// Minimum execution time: 29_114_225_000 picoseconds.
		Weight::from_parts(29_338_229_000, 0)
			.saturating_add(Weight::from_parts(0, 4657))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `PeopleLite::AttestationAllowance` (r:1 w:1)
	/// Proof: `PeopleLite::AttestationAllowance` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn increase_attestation_allowance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3`
		//  Estimated: `3517`
		// Minimum execution time: 9_927_000 picoseconds.
		Weight::from_parts(10_664_000, 0)
			.saturating_add(Weight::from_parts(0, 3517))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `PeopleLite::AttestationAllowance` (r:0 w:1)
	/// Proof: `PeopleLite::AttestationAllowance` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn clear_attestation_allowance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_028_000 picoseconds.
		Weight::from_parts(7_595_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Resources::Consumers` (r:1 w:1)
	/// Proof: `Resources::Consumers` (`max_values`: None, `max_size`: Some(155), added: 2630, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:1 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a8a88e3dd7409f195fd52db` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a8a88e3dd7409f195fd52db` (r:1 w:1)
	fn register_lite_consumer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3620`
		// Minimum execution time: 59_986_000 picoseconds.
		Weight::from_parts(65_133_000, 0)
			.saturating_add(Weight::from_parts(0, 3620))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `PeopleLite::LitePeople` (r:1 w:1)
	/// Proof: `PeopleLite::LitePeople` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `PeopleLite::AccountToAlias` (r:1 w:0)
	/// Proof: `PeopleLite::AccountToAlias` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Members::Members` (r:1 w:1)
	/// Proof: `Members::Members` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `PeopleLite::AttestationAllowance` (r:1 w:1)
	/// Proof: `PeopleLite::AttestationAllowance` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `PeopleLite::LitePeopleCollectionCreated` (r:1 w:0)
	/// Proof: `PeopleLite::LitePeopleCollectionCreated` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::QueuePageIndices` (r:1 w:1)
	/// Proof: `Members::QueuePageIndices` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `Members::OnboardingQueue` (r:1 w:1)
	/// Proof: `Members::OnboardingQueue` (`max_values`: None, `max_size`: Some(8206), added: 10681, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn attest() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `354`
		//  Estimated: `11671`
		// Minimum execution time: 2_653_174_000 picoseconds.
		Weight::from_parts(2_700_101_000, 0)
			.saturating_add(Weight::from_parts(0, 11671))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `PeopleLite::LitePeople` (r:1 w:1)
	/// Proof: `PeopleLite::LitePeople` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `PeopleLite::AccountToAlias` (r:1 w:0)
	/// Proof: `PeopleLite::AccountToAlias` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Members::Members` (r:1 w:1)
	/// Proof: `Members::Members` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `PeopleLite::LitePeopleCollectionCreated` (r:1 w:0)
	/// Proof: `PeopleLite::LitePeopleCollectionCreated` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Parameters::Parameters` (r:1 w:0)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::QueuePageIndices` (r:1 w:1)
	/// Proof: `Members::QueuePageIndices` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `Members::OnboardingQueue` (r:1 w:1)
	/// Proof: `Members::OnboardingQueue` (`max_values`: None, `max_size`: Some(8206), added: 10681, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn register_with_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `280`
		//  Estimated: `11671`
		// Minimum execution time: 2_601_799_000 picoseconds.
		Weight::from_parts(2_647_276_000, 0)
			.saturating_add(Weight::from_parts(0, 11671))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	fn dispatch_as_signer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_632_000 picoseconds.
		Weight::from_parts(5_093_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// Storage: `NetworkSuffix::NetworkSuffix` (r:1 w:0)
	/// Proof: `NetworkSuffix::NetworkSuffix` (`max_values`: Some(1), `max_size`: Some(17), added: 512, mode: `MaxEncodedLen`)
	/// Storage: `PeopleLite::LitePeople` (r:1 w:0)
	/// Proof: `PeopleLite::LitePeople` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `PeopleLite::AliasToAccount` (r:1 w:1)
	/// Proof: `PeopleLite::AliasToAccount` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `PeopleLite::AccountToAlias` (r:2 w:2)
	/// Proof: `PeopleLite::AccountToAlias` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn set_alias_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `582`
		//  Estimated: `6196`
		// Minimum execution time: 67_748_000 picoseconds.
		Weight::from_parts(69_680_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `PeopleLite::AliasToAccount` (r:1 w:1)
	/// Proof: `PeopleLite::AliasToAccount` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `PeopleLite::AccountToAlias` (r:0 w:1)
	/// Proof: `PeopleLite::AccountToAlias` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	fn unset_alias_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `331`
		//  Estimated: `3593`
		// Minimum execution time: 35_410_000 picoseconds.
		Weight::from_parts(37_383_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Members::Collections` (r:1 w:1)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::SuspendedCollections` (r:1 w:0)
	/// Proof: `Members::SuspendedCollections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::IdentifiersOf` (r:1 w:1)
	/// Proof: `Members::IdentifiersOf` (`max_values`: None, `max_size`: Some(3821), added: 6296, mode: `MaxEncodedLen`)
	/// Storage: `PeopleLite::LitePeopleCollectionCreated` (r:0 w:1)
	/// Proof: `PeopleLite::LitePeopleCollectionCreated` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingsState` (r:0 w:1)
	/// Proof: `Members::RingsState` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `Members::OnboardingSize` (r:0 w:1)
	/// Proof: `Members::OnboardingSize` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn create_lite_people_collection() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `7286`
		// Minimum execution time: 18_051_000 picoseconds.
		Weight::from_parts(19_248_000, 0)
			.saturating_add(Weight::from_parts(0, 7286))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `PeopleLite::LitePeopleCollectionCreated` (r:1 w:0)
	/// Proof: `PeopleLite::LitePeopleCollectionCreated` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn authorize_create_lite_people_collection() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3`
		//  Estimated: `1486`
		// Minimum execution time: 2_072_000 picoseconds.
		Weight::from_parts(2_330_000, 0)
			.saturating_add(Weight::from_parts(0, 1486))
			.saturating_add(T::DbWeight::get().reads(1))
	}
}
