// Copyright (C) Parity Technologies (UK) Ltd.
// This file is part of Individuality.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `indiv_pallet_members_notifier`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 57.0.0
//! DATE: 2026-08-15, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `parity-weights-67eb1984106a5c71`, CPU: `Intel(R) Xeon(R) CPU @ 2.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --extrinsic=*
// --runtime=target/production/wbuild/next-people-paseo-runtime/next_people_paseo_runtime.wasm
// --pallet=indiv_pallet_members_notifier
// --header=/home/runner/actions-runner/_work/individuality/individuality/.github/scripts/cmd/file_header.txt
// --output=./runtimes/next-people-paseo/src/weights
// --wasm-execution=compiled
// --steps=50
// --repeat=20
// --min-duration=1
// --heap-pages=4096
// --genesis-builder=runtime
// --no-storage-info
// --no-min-squares
// --no-median-slopes

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `indiv_pallet_members_notifier`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> indiv_pallet_members_notifier::WeightInfo for WeightInfo<T> {
	/// Storage: `MembersNotifier::Subscribers` (r:11 w:1)
	/// Proof: `MembersNotifier::Subscribers` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::CounterForSubscribers` (r:1 w:1)
	/// Proof: `MembersNotifier::CounterForSubscribers` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::SealedBatchSequence` (r:1 w:0)
	/// Proof: `MembersNotifier::SealedBatchSequence` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::PendingInit` (r:1 w:1)
	/// Proof: `MembersNotifier::PendingInit` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::CounterForPendingInit` (r:1 w:1)
	/// Proof: `MembersNotifier::CounterForPendingInit` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::SubscribedCollections` (r:27 w:30)
	/// Proof: `MembersNotifier::SubscribedCollections` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::SubscriptionWhitelist` (r:0 w:1)
	/// Proof: `MembersNotifier::SubscriptionWhitelist` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	fn subscribe() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2108`
		//  Estimated: `68679`
		// Minimum execution time: 118_883_000 picoseconds.
		Weight::from_parts(126_739_000, 0)
			.saturating_add(Weight::from_parts(0, 68679))
			.saturating_add(T::DbWeight::get().reads(43))
			.saturating_add(T::DbWeight::get().writes(35))
	}
	/// Storage: `MembersNotifier::SubscriptionWhitelist` (r:1 w:1)
	/// Proof: `MembersNotifier::SubscriptionWhitelist` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::Subscribers` (r:11 w:1)
	/// Proof: `MembersNotifier::Subscribers` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::CounterForSubscribers` (r:1 w:1)
	/// Proof: `MembersNotifier::CounterForSubscribers` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::SealedBatchSequence` (r:1 w:0)
	/// Proof: `MembersNotifier::SealedBatchSequence` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::PendingInit` (r:1 w:1)
	/// Proof: `MembersNotifier::PendingInit` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::CounterForPendingInit` (r:1 w:1)
	/// Proof: `MembersNotifier::CounterForPendingInit` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::SubscribedCollections` (r:27 w:30)
	/// Proof: `MembersNotifier::SubscribedCollections` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	fn subscribe_whitelisted() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2240`
		//  Estimated: `68679`
		// Minimum execution time: 123_731_000 picoseconds.
		Weight::from_parts(129_688_000, 0)
			.saturating_add(Weight::from_parts(0, 68679))
			.saturating_add(T::DbWeight::get().reads(44))
			.saturating_add(T::DbWeight::get().writes(35))
	}
	/// Storage: `MembersNotifier::Subscribers` (r:11 w:1)
	/// Proof: `MembersNotifier::Subscribers` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `XcmpQueue::DeliveryFeeFactor` (r:1 w:0)
	/// Proof: `XcmpQueue::DeliveryFeeFactor` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `PolkadotXcm::SupportedVersion` (r:1 w:0)
	/// Proof: `PolkadotXcm::SupportedVersion` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `XcmpQueue::OutboundXcmpStatus` (r:1 w:1)
	/// Proof: `XcmpQueue::OutboundXcmpStatus` (`max_values`: Some(1), `max_size`: Some(1794), added: 2289, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::RelevantMessagingState` (r:1 w:0)
	/// Proof: `ParachainSystem::RelevantMessagingState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `MembersNotifier::CounterForSubscribers` (r:1 w:1)
	/// Proof: `MembersNotifier::CounterForSubscribers` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::PendingInit` (r:1 w:1)
	/// Proof: `MembersNotifier::PendingInit` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::CounterForPendingInit` (r:1 w:1)
	/// Proof: `MembersNotifier::CounterForPendingInit` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::SubscribedCollections` (r:30 w:30)
	/// Proof: `MembersNotifier::SubscribedCollections` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::LastReplayTime` (r:3 w:3)
	/// Proof: `MembersNotifier::LastReplayTime` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::CurrentBatch` (r:1 w:1)
	/// Proof: `MembersNotifier::CurrentBatch` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::SubscribersWithCurrentBatch` (r:10 w:9)
	/// Proof: `MembersNotifier::SubscribersWithCurrentBatch` (`max_values`: None, `max_size`: Some(4), added: 2479, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::SealedBatchIndices` (r:10 w:10)
	/// Proof: `MembersNotifier::SealedBatchIndices` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `XcmpQueue::OutboundXcmpMessages` (r:0 w:1)
	/// Proof: `XcmpQueue::OutboundXcmpMessages` (`max_values`: None, `max_size`: Some(105506), added: 107981, mode: `MaxEncodedLen`)
	fn unsubscribe() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3938`
		//  Estimated: `76200`
		// Minimum execution time: 185_792_000 picoseconds.
		Weight::from_parts(194_213_000, 0)
			.saturating_add(Weight::from_parts(0, 76200))
			.saturating_add(T::DbWeight::get().reads(72))
			.saturating_add(T::DbWeight::get().writes(59))
	}
	/// Storage: `MembersNotifier::Subscribers` (r:1 w:0)
	/// Proof: `MembersNotifier::Subscribers` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `Members::CurrentRingIndex` (r:1 w:0)
	/// Proof: `Members::CurrentRingIndex` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Members::Root` (r:10 w:0)
	/// Proof: `Members::Root` (`max_values`: None, `max_size`: Some(1192), added: 3667, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::RelevantMessagingState` (r:1 w:0)
	/// Proof: `ParachainSystem::RelevantMessagingState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::LastReplayTime` (r:1 w:1)
	/// Proof: `MembersNotifier::LastReplayTime` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::SealedBatchSequence` (r:1 w:0)
	/// Proof: `MembersNotifier::SealedBatchSequence` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `XcmpQueue::DeliveryFeeFactor` (r:1 w:0)
	/// Proof: `XcmpQueue::DeliveryFeeFactor` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `PolkadotXcm::SupportedVersion` (r:1 w:0)
	/// Proof: `PolkadotXcm::SupportedVersion` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `XcmpQueue::OutboundXcmpStatus` (r:1 w:1)
	/// Proof: `XcmpQueue::OutboundXcmpStatus` (`max_values`: Some(1), `max_size`: Some(1794), added: 2289, mode: `MaxEncodedLen`)
	/// Storage: `XcmpQueue::OutboundXcmpMessages` (r:0 w:1)
	/// Proof: `XcmpQueue::OutboundXcmpMessages` (`max_values`: None, `max_size`: Some(105506), added: 107981, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	fn request_replay(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7538 + n * (112176 ±0)`
		//  Estimated: `10916 + n * (112179 ±0)`
		// Minimum execution time: 108_032_000 picoseconds.
		Weight::from_parts(89_009_884, 0)
			.saturating_add(Weight::from_parts(0, 10916))
			// Standard Error: 126_666
			.saturating_add(Weight::from_parts(28_729_815, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(3))
			.saturating_add(Weight::from_parts(0, 112179).saturating_mul(n.into()))
	}
	/// Storage: `MembersNotifier::PageState` (r:1 w:1)
	/// Proof: `MembersNotifier::PageState` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::PendingUpdates` (r:11 w:10)
	/// Proof: `MembersNotifier::PendingUpdates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::SubscribedCollections` (r:10 w:0)
	/// Proof: `MembersNotifier::SubscribedCollections` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::CounterForSubscribers` (r:1 w:0)
	/// Proof: `MembersNotifier::CounterForSubscribers` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::SealedBatchSequence` (r:1 w:1)
	/// Proof: `MembersNotifier::SealedBatchSequence` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::CurrentBatch` (r:0 w:1)
	/// Proof: `MembersNotifier::CurrentBatch` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::SealedBatchIndices` (r:0 w:10)
	/// Proof: `MembersNotifier::SealedBatchIndices` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::PageUpdatesCount` (r:0 w:1)
	/// Proof: `MembersNotifier::PageUpdatesCount` (`max_values`: None, `max_size`: Some(6), added: 2481, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	fn enqueue_updates(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1356 + n * (38 ±0)`
		//  Estimated: `3503 + n * (2513 ±0)`
		// Minimum execution time: 62_162_000 picoseconds.
		Weight::from_parts(57_653_137, 0)
			.saturating_add(Weight::from_parts(0, 3503))
			// Standard Error: 65_954
			.saturating_add(Weight::from_parts(12_610_781, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2513).saturating_mul(n.into()))
	}
	/// Storage: `MembersNotifier::CurrentBatch` (r:1 w:1)
	/// Proof: `MembersNotifier::CurrentBatch` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::Subscribers` (r:1 w:0)
	/// Proof: `MembersNotifier::Subscribers` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::RelevantMessagingState` (r:1 w:0)
	/// Proof: `ParachainSystem::RelevantMessagingState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `MembersNotifier::SealedBatchIndices` (r:10 w:10)
	/// Proof: `MembersNotifier::SealedBatchIndices` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Members::Root` (r:12 w:0)
	/// Proof: `Members::Root` (`max_values`: None, `max_size`: Some(1192), added: 3667, mode: `MaxEncodedLen`)
	/// Storage: `Members::CurrentRingIndex` (r:3 w:0)
	/// Proof: `Members::CurrentRingIndex` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `XcmpQueue::DeliveryFeeFactor` (r:1 w:0)
	/// Proof: `XcmpQueue::DeliveryFeeFactor` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `PolkadotXcm::SupportedVersion` (r:1 w:0)
	/// Proof: `PolkadotXcm::SupportedVersion` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `XcmpQueue::OutboundXcmpStatus` (r:1 w:1)
	/// Proof: `XcmpQueue::OutboundXcmpStatus` (`max_values`: Some(1), `max_size`: Some(1794), added: 2289, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::SubscribersWithCurrentBatch` (r:10 w:11)
	/// Proof: `MembersNotifier::SubscribersWithCurrentBatch` (`max_values`: None, `max_size`: Some(4), added: 2479, mode: `MaxEncodedLen`)
	/// Storage: `XcmpQueue::OutboundXcmpMessages` (r:0 w:10)
	/// Proof: `XcmpQueue::OutboundXcmpMessages` (`max_values`: None, `max_size`: Some(105506), added: 107981, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[3, 10]`.
	fn send_batch(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `8165 + n * (112180 ±0)`
		//  Estimated: `26470 + n * (112165 ±0)`
		// Minimum execution time: 254_077_000 picoseconds.
		Weight::from_parts(124_786_814, 0)
			.saturating_add(Weight::from_parts(0, 26470))
			// Standard Error: 145_171
			.saturating_add(Weight::from_parts(52_182_894, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(31))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(23))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 112165).saturating_mul(n.into()))
	}
	/// Storage: `MembersNotifier::PendingInit` (r:1 w:1)
	/// Proof: `MembersNotifier::PendingInit` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::RelevantMessagingState` (r:1 w:0)
	/// Proof: `ParachainSystem::RelevantMessagingState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Members::Root` (r:11 w:0)
	/// Proof: `Members::Root` (`max_values`: None, `max_size`: Some(1192), added: 3667, mode: `MaxEncodedLen`)
	/// Storage: `Members::CurrentRingIndex` (r:1 w:0)
	/// Proof: `Members::CurrentRingIndex` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `XcmpQueue::DeliveryFeeFactor` (r:1 w:0)
	/// Proof: `XcmpQueue::DeliveryFeeFactor` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `PolkadotXcm::SupportedVersion` (r:1 w:0)
	/// Proof: `PolkadotXcm::SupportedVersion` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `XcmpQueue::OutboundXcmpStatus` (r:1 w:1)
	/// Proof: `XcmpQueue::OutboundXcmpStatus` (`max_values`: Some(1), `max_size`: Some(1794), added: 2289, mode: `MaxEncodedLen`)
	/// Storage: `XcmpQueue::OutboundXcmpMessages` (r:0 w:1)
	/// Proof: `XcmpQueue::OutboundXcmpMessages` (`max_values`: None, `max_size`: Some(105506), added: 107981, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::CounterForPendingInit` (r:1 w:1)
	/// Proof: `MembersNotifier::CounterForPendingInit` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	fn send_init_page(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7436 + n * (112176 ±0)`
		//  Estimated: `10815 + n * (112179 ±0)`
		// Minimum execution time: 106_518_000 picoseconds.
		Weight::from_parts(88_069_113, 0)
			.saturating_add(Weight::from_parts(0, 10815))
			// Standard Error: 127_831
			.saturating_add(Weight::from_parts(29_743_783, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(Weight::from_parts(0, 112179).saturating_mul(n.into()))
	}
	/// Storage: `MembersNotifier::CurrentBatch` (r:1 w:1)
	/// Proof: `MembersNotifier::CurrentBatch` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::SealedBatchIndices` (r:10 w:10)
	/// Proof: `MembersNotifier::SealedBatchIndices` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::SubscribersWithCurrentBatch` (r:10 w:10)
	/// Proof: `MembersNotifier::SubscribersWithCurrentBatch` (`max_values`: None, `max_size`: Some(4), added: 2479, mode: `MaxEncodedLen`)
	fn abandon_stuck_batch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `831`
		//  Estimated: `26470`
		// Minimum execution time: 30_279_000 picoseconds.
		Weight::from_parts(32_504_000, 0)
			.saturating_add(Weight::from_parts(0, 26470))
			.saturating_add(T::DbWeight::get().reads(21))
			.saturating_add(T::DbWeight::get().writes(21))
	}
	/// Storage: `MembersNotifier::PageState` (r:1 w:0)
	/// Proof: `MembersNotifier::PageState` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::CurrentBatch` (r:1 w:0)
	/// Proof: `MembersNotifier::CurrentBatch` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::PageUpdatesCount` (r:1 w:0)
	/// Proof: `MembersNotifier::PageUpdatesCount` (`max_values`: None, `max_size`: Some(6), added: 2481, mode: `MaxEncodedLen`)
	fn authorize_enqueue_updates() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `103`
		//  Estimated: `3471`
		// Minimum execution time: 7_909_000 picoseconds.
		Weight::from_parts(8_501_000, 0)
			.saturating_add(Weight::from_parts(0, 3471))
			.saturating_add(T::DbWeight::get().reads(3))
	}
	/// Storage: `MembersNotifier::CurrentBatch` (r:1 w:0)
	/// Proof: `MembersNotifier::CurrentBatch` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::SubscribersWithCurrentBatch` (r:1 w:0)
	/// Proof: `MembersNotifier::SubscribersWithCurrentBatch` (`max_values`: None, `max_size`: Some(4), added: 2479, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::Subscribers` (r:1 w:0)
	/// Proof: `MembersNotifier::Subscribers` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	fn authorize_send_batch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `181`
		//  Estimated: `3578`
		// Minimum execution time: 9_663_000 picoseconds.
		Weight::from_parts(10_383_000, 0)
			.saturating_add(Weight::from_parts(0, 3578))
			.saturating_add(T::DbWeight::get().reads(3))
	}
	/// Storage: `MembersNotifier::PendingInit` (r:1 w:0)
	/// Proof: `MembersNotifier::PendingInit` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	fn authorize_send_init_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `158`
		//  Estimated: `3595`
		// Minimum execution time: 6_891_000 picoseconds.
		Weight::from_parts(7_498_000, 0)
			.saturating_add(Weight::from_parts(0, 3595))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `MembersNotifier::CurrentBatch` (r:1 w:0)
	/// Proof: `MembersNotifier::CurrentBatch` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	fn authorize_abandon_stuck_batch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `85`
		//  Estimated: `1509`
		// Minimum execution time: 4_643_000 picoseconds.
		Weight::from_parts(5_047_000, 0)
			.saturating_add(Weight::from_parts(0, 1509))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `MembersNotifier::SubscriptionWhitelist` (r:1 w:0)
	/// Proof: `MembersNotifier::SubscriptionWhitelist` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::Subscribers` (r:1 w:0)
	/// Proof: `MembersNotifier::Subscribers` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::CounterForSubscribers` (r:1 w:0)
	/// Proof: `MembersNotifier::CounterForSubscribers` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn authorize_subscribe_whitelisted() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `293`
		//  Estimated: `3578`
		// Minimum execution time: 12_510_000 picoseconds.
		Weight::from_parts(13_378_000, 0)
			.saturating_add(Weight::from_parts(0, 3578))
			.saturating_add(T::DbWeight::get().reads(3))
	}
}
