// Copyright (C) Parity Technologies (UK) Ltd.
// This file is part of Individuality.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `indiv_pallet_nft_credits`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 57.0.0
//! DATE: 2026-08-07, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `parity-weights-631de83113a5a1bb`, CPU: `Intel(R) Xeon(R) CPU @ 2.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --extrinsic=*
// --runtime=target/production/wbuild/next-people-paseo-runtime/next_people_paseo_runtime.wasm
// --pallet=indiv_pallet_nft_credits
// --header=/home/runner/actions-runner/_work/individuality/individuality/.github/scripts/cmd/file_header.txt
// --output=./runtimes/next-people-paseo/src/weights
// --wasm-execution=compiled
// --steps=50
// --repeat=20
// --min-duration=1
// --heap-pages=4096
// --genesis-builder=runtime
// --no-storage-info
// --no-min-squares
// --no-median-slopes

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `indiv_pallet_nft_credits`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> indiv_pallet_nft_credits::WeightInfo for WeightInfo<T> {
	/// Storage: `NftCredits::PendingNftClaimCreditRootInfo` (r:1 w:1)
	/// Proof: `NftCredits::PendingNftClaimCreditRootInfo` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NftCredits::NftClaimCreditAwards` (r:1 w:1)
	/// Proof: `NftCredits::NftClaimCreditAwards` (`max_values`: None, `max_size`: Some(78014), added: 80489, mode: `MaxEncodedLen`)
	/// Storage: `NftCredits::NftClaimCreditAwardBlocks` (r:1 w:1)
	/// Proof: `NftCredits::NftClaimCreditAwardBlocks` (`max_values`: Some(1), `max_size`: Some(1026), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `NftCredits::NextCreditTreeSequence` (r:1 w:1)
	/// Proof: `NftCredits::NextCreditTreeSequence` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NftCredits::CreditTreeDeliveryQueue` (r:1 w:1)
	/// Proof: `NftCredits::CreditTreeDeliveryQueue` (`max_values`: Some(1), `max_size`: Some(3074), added: 3569, mode: `MaxEncodedLen`)
	/// Storage: `NftCredits::NftClaimCreditRoots` (r:0 w:1)
	/// Proof: `NftCredits::NftClaimCreditRoots` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 1200]`.
	fn build_credit_tree(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1275 + n * (65 ±0)`
		//  Estimated: `81479`
		// Minimum execution time: 29_280_000 picoseconds.
		Weight::from_parts(28_731_791, 0)
			.saturating_add(Weight::from_parts(0, 81479))
			// Standard Error: 1_549
			.saturating_add(Weight::from_parts(998_748, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `NftCredits::PendingNftClaimCreditRootInfo` (r:1 w:0)
	/// Proof: `NftCredits::PendingNftClaimCreditRootInfo` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn build_credit_tree_empty() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `114`
		//  Estimated: `1493`
		// Minimum execution time: 3_018_000 picoseconds.
		Weight::from_parts(3_334_000, 0)
			.saturating_add(Weight::from_parts(0, 1493))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `NftCredits::CreditTreeDeliveryQueue` (r:1 w:1)
	/// Proof: `NftCredits::CreditTreeDeliveryQueue` (`max_values`: Some(1), `max_size`: Some(3074), added: 3569, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::RelevantMessagingState` (r:1 w:0)
	/// Proof: `ParachainSystem::RelevantMessagingState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `NftCredits::NftClaimCreditRoots` (r:32 w:0)
	/// Proof: `NftCredits::NftClaimCreditRoots` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `XcmpQueue::DeliveryFeeFactor` (r:1 w:0)
	/// Proof: `XcmpQueue::DeliveryFeeFactor` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `PolkadotXcm::SupportedVersion` (r:1 w:0)
	/// Proof: `PolkadotXcm::SupportedVersion` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `XcmpQueue::OutboundXcmpStatus` (r:1 w:1)
	/// Proof: `XcmpQueue::OutboundXcmpStatus` (`max_values`: Some(1), `max_size`: Some(1794), added: 2289, mode: `MaxEncodedLen`)
	/// Storage: `XcmpQueue::OutboundXcmpMessages` (r:0 w:1)
	/// Proof: `XcmpQueue::OutboundXcmpMessages` (`max_values`: None, `max_size`: Some(105506), added: 107981, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 32]`.
	fn send_credit_trees(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `5237 + n * (188 ±0)`
		//  Estimated: `8592 + n * (2531 ±6)`
		// Minimum execution time: 72_857_000 picoseconds.
		Weight::from_parts(74_992_339, 0)
			.saturating_add(Weight::from_parts(0, 8592))
			// Standard Error: 19_937
			.saturating_add(Weight::from_parts(5_151_155, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(3))
			.saturating_add(Weight::from_parts(0, 2531).saturating_mul(n.into()))
	}
	/// Storage: `ParachainSystem::RelevantMessagingState` (r:1 w:0)
	/// Proof: `ParachainSystem::RelevantMessagingState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `NftCredits::NftClaimCreditRoots` (r:32 w:0)
	/// Proof: `NftCredits::NftClaimCreditRoots` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `XcmpQueue::DeliveryFeeFactor` (r:1 w:0)
	/// Proof: `XcmpQueue::DeliveryFeeFactor` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `PolkadotXcm::SupportedVersion` (r:1 w:0)
	/// Proof: `PolkadotXcm::SupportedVersion` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `XcmpQueue::OutboundXcmpStatus` (r:1 w:1)
	/// Proof: `XcmpQueue::OutboundXcmpStatus` (`max_values`: Some(1), `max_size`: Some(1794), added: 2289, mode: `MaxEncodedLen`)
	/// Storage: `XcmpQueue::OutboundXcmpMessages` (r:0 w:1)
	/// Proof: `XcmpQueue::OutboundXcmpMessages` (`max_values`: None, `max_size`: Some(105506), added: 107981, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 32]`.
	fn replay_credit_trees(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `434 + n * (63 ±0)`
		//  Estimated: `3900 + n * (2531 ±0)`
		// Minimum execution time: 46_048_000 picoseconds.
		Weight::from_parts(44_411_295, 0)
			.saturating_add(Weight::from_parts(0, 3900))
			// Standard Error: 6_803
			.saturating_add(Weight::from_parts(3_956_939, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(Weight::from_parts(0, 2531).saturating_mul(n.into()))
	}
	/// Storage: `NftCredits::CreditTreeDeliveryQueue` (r:1 w:0)
	/// Proof: `NftCredits::CreditTreeDeliveryQueue` (`max_values`: Some(1), `max_size`: Some(3074), added: 3569, mode: `MaxEncodedLen`)
	fn authorize_send_credit_trees() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3276`
		//  Estimated: `4559`
		// Minimum execution time: 10_339_000 picoseconds.
		Weight::from_parts(10_929_000, 0)
			.saturating_add(Weight::from_parts(0, 4559))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `NftCredits::PrivateGames` (r:1 w:1)
	/// Storage: `NftCredits::PrivateCreditBalances` (r:1 w:1)
	/// Storage: `NftCredits::PrivateRegistrations` (r:1 w:1)
	/// Storage: `NftCredits::PrivateRingKeys` (r:1 w:1)
	fn register_private_claim_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `9000`
		//  Estimated: `12480`
		// Minimum execution time: 45_000_000 picoseconds.
		Weight::from_parts(45_000_000, 0)
			.saturating_add(Weight::from_parts(0, 12480))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `NftCredits::PrivateGames` (r:1 w:1)
	/// Storage: `NftCredits::PrivateRingKeys` (r:1 w:0)
	/// Storage: `NftCredits::PrivateRingIntermediates` (r:1 w:1)
	/// Storage: `ChunksManager::Chunks` (r:1 w:0)
	/// The range of component `n` is `[1, 8]`.
	fn build_private_ring(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `20000`
		//  Estimated: `80000`
		// Minimum execution time: 200_000_000 picoseconds.
		Weight::from_parts(200_000_000, 0)
			.saturating_add(Weight::from_parts(0, 80000))
			// Standard Error: 1_000_000
			.saturating_add(Weight::from_parts(90_000_000, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `NftCredits::PrivateGames` (r:1 w:1)
	/// Storage: `NftCredits::PrivateRingKeys` (r:1 w:0)
	/// Storage: `NftCredits::PrivateRingIntermediates` (r:1 w:1)
	/// Storage: `NftCredits::PrivateRings` (r:0 w:1)
	/// Storage: `NftCredits::PrivateRingDeliveryQueue` (r:1 w:1)
	fn finish_private_ring() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `20000`
		//  Estimated: `80000`
		// Minimum execution time: 150_000_000 picoseconds.
		Weight::from_parts(150_000_000, 0)
			.saturating_add(Weight::from_parts(0, 80000))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `NftCredits::PrivateGames` (r:1 w:0)
	/// Storage: `NftCredits::PrivateRingKeys` (r:1 w:0)
	fn authorize_build_private_ring() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `20000`
		//  Estimated: `80000`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(15_000_000, 0)
			.saturating_add(Weight::from_parts(0, 80000))
			.saturating_add(T::DbWeight::get().reads(2))
	}
	/// Storage: `NftCredits::PrivateRings` (r:1 w:1)
	/// Storage: `NftCredits::PrivateRingDeliveryQueue` (r:1 w:1)
	fn send_private_ring() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `20000`
		//  Estimated: `80000`
		// Minimum execution time: 60_000_000 picoseconds.
		Weight::from_parts(60_000_000, 0)
			.saturating_add(Weight::from_parts(0, 80000))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `NftCredits::PrivateRingDeliveryQueue` (r:1 w:0)
	fn authorize_send_private_ring() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1000`
		//  Estimated: `4489`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4489))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `NftCredits::PrivateGames` (r:1 w:1)
	/// Storage: `NftCredits::PrivateRingKeys` (r:0 w:1)
	/// Storage: `NftCredits::PrivateRegistrations` (r:33 w:32)
	/// Storage: `NftCredits::PrivateCreditBalances` (r:33 w:32)
	/// The range of component `n` is `[0, 32]`.
	fn clean_up_private_game(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `20000`
		//  Estimated: `80000`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(20_000_000, 0)
			.saturating_add(Weight::from_parts(0, 80000))
			// Standard Error: 100_000
			.saturating_add(Weight::from_parts(2_000_000, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
	}
	/// Storage: `NftCredits::PrivateGames` (r:1 w:0)
	fn authorize_clean_up_private_game() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1000`
		//  Estimated: `4489`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4489))
			.saturating_add(T::DbWeight::get().reads(1))
	}
}
