// Copyright (C) Parity Technologies (UK) Ltd.
// This file is part of Individuality.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `indiv_pallet_game`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 60.0.0
//! DATE: 2026-10-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `parity-weights-966e84b92e8679de`, CPU: `Intel(R) Xeon(R) CPU @ 2.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --extrinsic=*
// --runtime=target/production/wbuild/next-people-paseo-runtime/next_people_paseo_runtime.wasm
// --pallet=indiv_pallet_game
// --header=/home/runner/actions-runner/_work/individuality-community/individuality-community/.github/scripts/cmd/file_header.txt
// --output=./runtimes/next-people-paseo/src/weights
// --wasm-execution=compiled
// --steps=50
// --repeat=20
// --min-duration=1
// --heap-pages=4096
// --genesis-builder=runtime
// --no-storage-info
// --no-min-squares
// --no-median-slopes

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `indiv_pallet_game`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> indiv_pallet_game::WeightInfo for WeightInfo<T> {
	/// Storage: `Game::GameSchedules` (r:1 w:1)
	/// Proof: `Game::GameSchedules` (`max_values`: Some(1), `max_size`: Some(121849), added: 122344, mode: `MaxEncodedLen`)
	/// Storage: `Game::Game` (r:1 w:1)
	/// Proof: `Game::Game` (`max_values`: Some(1), `max_size`: Some(74), added: 569, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Game::StoredPhaseDurations` (r:1 w:0)
	/// Proof: `Game::StoredPhaseDurations` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Game::GameIndex` (r:1 w:1)
	/// Proof: `Game::GameIndex` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:2 w:1)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(682), added: 3157, mode: `MaxEncodedLen`)
	/// Storage: `Airdrop::SupportedAssets` (r:1 w:0)
	/// Proof: `Airdrop::SupportedAssets` (`max_values`: None, `max_size`: Some(626), added: 3101, mode: `MaxEncodedLen`)
	/// Storage: `Airdrop::Events` (r:16 w:16)
	/// Proof: `Airdrop::Events` (`max_values`: None, `max_size`: Some(800), added: 3275, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::Holds` (r:1 w:1)
	/// Proof: `AssetsHolder::Holds` (`max_values`: None, `max_size`: Some(883), added: 3358, mode: `MaxEncodedLen`)
	/// Storage: `Game::GameHistory` (r:0 w:1)
	/// Proof: `Game::GameHistory` (`max_values`: None, `max_size`: Some(16), added: 2491, mode: `MaxEncodedLen`)
	/// Storage: `Airdrop::ActionSchedule` (r:0 w:16)
	/// Proof: `Airdrop::ActionSchedule` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	fn start_game() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `9387`
		//  Estimated: `123334`
		// Minimum execution time: 1_548_530_000 picoseconds.
		Weight::from_parts(1_618_561_000, 0)
			.saturating_add(Weight::from_parts(0, 123334))
			.saturating_add(T::DbWeight::get().reads(28))
			.saturating_add(T::DbWeight::get().writes(41))
	}
	/// Storage: `Game::GameIndex` (r:1 w:0)
	/// Proof: `Game::GameIndex` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Game::Game` (r:1 w:1)
	/// Proof: `Game::Game` (`max_values`: Some(1), `max_size`: Some(74), added: 569, mode: `MaxEncodedLen`)
	fn end_registration_shuffle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `297`
		//  Estimated: `1559`
		// Minimum execution time: 12_643_000 picoseconds.
		Weight::from_parts(13_640_000, 0)
			.saturating_add(Weight::from_parts(0, 1559))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Game::GameIndex` (r:1 w:0)
	/// Proof: `Game::GameIndex` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Game::Game` (r:1 w:1)
	/// Proof: `Game::Game` (`max_values`: Some(1), `max_size`: Some(74), added: 569, mode: `MaxEncodedLen`)
	/// Storage: `Airdrop::Events` (r:16 w:16)
	/// Proof: `Airdrop::Events` (`max_values`: None, `max_size`: Some(800), added: 3275, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::Holds` (r:1 w:1)
	/// Proof: `AssetsHolder::Holds` (`max_values`: None, `max_size`: Some(883), added: 3358, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:1)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(682), added: 3157, mode: `MaxEncodedLen`)
	/// Storage: `Airdrop::ActionSchedule` (r:0 w:16)
	/// Proof: `Airdrop::ActionSchedule` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 16]`.
	fn end_registration_cancel(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1081 + n * (174 ±0)`
		//  Estimated: `7404 + n * (3275 ±0)`
		// Minimum execution time: 14_237_000 picoseconds.
		Weight::from_parts(41_857_467, 0)
			.saturating_add(Weight::from_parts(0, 7404))
			// Standard Error: 87_307
			.saturating_add(Weight::from_parts(70_191_067, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(5))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 3275).saturating_mul(n.into()))
	}
	/// Storage: `Game::GameIndex` (r:1 w:0)
	/// Proof: `Game::GameIndex` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Game::Game` (r:1 w:0)
	/// Proof: `Game::Game` (`max_values`: Some(1), `max_size`: Some(74), added: 569, mode: `MaxEncodedLen`)
	/// Storage: `Game::GameSchedules` (r:1 w:0)
	/// Proof: `Game::GameSchedules` (`max_values`: Some(1), `max_size`: Some(121849), added: 122344, mode: `MaxEncodedLen`)
	fn authorize_game_step() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `8705`
		//  Estimated: `123334`
		// Minimum execution time: 7_143_000 picoseconds.
		Weight::from_parts(7_650_000, 0)
			.saturating_add(Weight::from_parts(0, 123334))
			.saturating_add(T::DbWeight::get().reads(3))
	}
	/// Storage: `Game::GameIndex` (r:1 w:0)
	/// Proof: `Game::GameIndex` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Game::Game` (r:1 w:0)
	/// Proof: `Game::Game` (`max_values`: Some(1), `max_size`: Some(74), added: 569, mode: `MaxEncodedLen`)
	fn game_step_base() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `230`
		//  Estimated: `1559`
		// Minimum execution time: 6_894_000 picoseconds.
		Weight::from_parts(7_412_000, 0)
			.saturating_add(Weight::from_parts(0, 1559))
			.saturating_add(T::DbWeight::get().reads(2))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `System::ParentHash` (r:1 w:0)
	/// Proof: `System::ParentHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Game::Players` (r:1 w:0)
	/// Proof: `Game::Players` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Game::ShuffleRecognized` (r:1 w:0)
	/// Proof: `Game::ShuffleRecognized` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Game::ShuffleNotRecognized` (r:1 w:0)
	/// Proof: `Game::ShuffleNotRecognized` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Game::PlayerToIndex` (r:1 w:0)
	/// Proof: `Game::PlayerToIndex` (`max_values`: None, `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingsState` (r:1 w:0)
	/// Proof: `Members::RingsState` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `Members::ActiveMembers` (r:1 w:0)
	/// Proof: `Members::ActiveMembers` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Score::PersonhoodThresholdSchedule` (r:1 w:0)
	/// Proof: `Score::PersonhoodThresholdSchedule` (`max_values`: Some(1), `max_size`: Some(81), added: 576, mode: `MaxEncodedLen`)
	/// Storage: `Score::AbsenceGraceSchedule` (r:1 w:0)
	/// Proof: `Score::AbsenceGraceSchedule` (`max_values`: Some(1), `max_size`: Some(49), added: 544, mode: `MaxEncodedLen`)
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Score::AbsenceGraceRatio` (r:0 w:1)
	/// Proof: `Score::AbsenceGraceRatio` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `Score::PersonhoodThreshold` (r:0 w:1)
	/// Proof: `Score::PersonhoodThreshold` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Game::Game` (r:0 w:1)
	/// Proof: `Game::Game` (`max_values`: Some(1), `max_size`: Some(74), added: 569, mode: `MaxEncodedLen`)
	fn shuffles_base() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `425`
		//  Estimated: `4111`
		// Minimum execution time: 31_757_000 picoseconds.
		Weight::from_parts(33_615_000, 0)
			.saturating_add(Weight::from_parts(0, 4111))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Game::Players` (r:2 w:1)
	/// Proof: `Game::Players` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Score::Participants` (r:1 w:0)
	/// Proof: `Score::Participants` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Game::ShuffleNotRecognized` (r:0 w:10)
	/// Proof: `Game::ShuffleNotRecognized` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	fn shuffle_step_insert(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `672`
		//  Estimated: `6100`
		// Minimum execution time: 26_607_000 picoseconds.
		Weight::from_parts(25_999_509, 0)
			.saturating_add(Weight::from_parts(0, 6100))
			// Standard Error: 3_540
			.saturating_add(Weight::from_parts(2_135_994, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
	}
	/// Storage: `Game::ShuffleNotRecognized` (r:20 w:10)
	/// Proof: `Game::ShuffleNotRecognized` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Game::PlayerToIndex` (r:2 w:2)
	/// Proof: `Game::PlayerToIndex` (`max_values`: None, `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `Game::IndexToPlayer` (r:0 w:10)
	/// Proof: `Game::IndexToPlayer` (`max_values`: None, `max_size`: Some(46), added: 2521, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	fn shuffle_step_retrieve(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `399 + n * (90 ±0)`
		//  Estimated: `4891 + n * (5098 ±0)`
		// Minimum execution time: 21_960_000 picoseconds.
		Weight::from_parts(12_950_188, 0)
			.saturating_add(Weight::from_parts(0, 4891))
			// Standard Error: 32_873
			.saturating_add(Weight::from_parts(13_582_976, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 5098).saturating_mul(n.into()))
	}
	/// Storage: `Game::PlayerToIndex` (r:2 w:0)
	/// Proof: `Game::PlayerToIndex` (`max_values`: None, `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `Game::Players` (r:1 w:1)
	/// Proof: `Game::Players` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[2, 100]`.
	fn shuffle_step_compute_weights(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1151`
		//  Estimated: `6120`
		// Minimum execution time: 20_852_000 picoseconds.
		Weight::from_parts(25_526_060, 0)
			.saturating_add(Weight::from_parts(0, 6120))
			// Standard Error: 1_382
			.saturating_add(Weight::from_parts(43_818, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Members::RingsState` (r:1 w:0)
	/// Proof: `Members::RingsState` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `Members::ActiveMembers` (r:1 w:0)
	/// Proof: `Members::ActiveMembers` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Score::PersonhoodThresholdSchedule` (r:1 w:0)
	/// Proof: `Score::PersonhoodThresholdSchedule` (`max_values`: Some(1), `max_size`: Some(81), added: 576, mode: `MaxEncodedLen`)
	/// Storage: `Score::AbsenceGraceSchedule` (r:1 w:0)
	/// Proof: `Score::AbsenceGraceSchedule` (`max_values`: Some(1), `max_size`: Some(49), added: 544, mode: `MaxEncodedLen`)
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Score::AbsenceGraceRatio` (r:0 w:1)
	/// Proof: `Score::AbsenceGraceRatio` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `Score::PersonhoodThreshold` (r:0 w:1)
	/// Proof: `Score::PersonhoodThreshold` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn shuffle_step_start_session() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `458`
		//  Estimated: `4111`
		// Minimum execution time: 17_186_000 picoseconds.
		Weight::from_parts(18_383_000, 0)
			.saturating_add(Weight::from_parts(0, 4111))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Game::Game` (r:1 w:1)
	/// Proof: `Game::Game` (`max_values`: Some(1), `max_size`: Some(74), added: 569, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NftCredits::CreditBufferCursor` (r:1 w:0)
	/// Proof: `NftCredits::CreditBufferCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NftCredits::CreditBuffers` (r:1 w:0)
	/// Proof: `NftCredits::CreditBuffers` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `Game::Players` (r:1 w:0)
	/// Proof: `Game::Players` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	fn player_process_step1() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `460`
		//  Estimated: `4111`
		// Minimum execution time: 23_096_000 picoseconds.
		Weight::from_parts(24_896_000, 0)
			.saturating_add(Weight::from_parts(0, 4111))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Score::Participants` (r:1 w:1)
	/// Proof: `Score::Participants` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Score::PersonhoodThreshold` (r:1 w:0)
	/// Proof: `Score::PersonhoodThreshold` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Score::AbsenceGraceRatio` (r:1 w:0)
	/// Proof: `Score::AbsenceGraceRatio` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `Game::PlayerAttendanceHistory` (r:1 w:1)
	/// Proof: `Game::PlayerAttendanceHistory` (`max_values`: None, `max_size`: Some(98), added: 2573, mode: `MaxEncodedLen`)
	/// Storage: `Game::GameParticipantCount` (r:1 w:1)
	/// Proof: `Game::GameParticipantCount` (`max_values`: None, `max_size`: Some(16), added: 2491, mode: `MaxEncodedLen`)
	/// Storage: `Game::PlayerToIndex` (r:1 w:0)
	/// Proof: `Game::PlayerToIndex` (`max_values`: None, `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `Game::IndexToPlayer` (r:90 w:0)
	/// Proof: `Game::IndexToPlayer` (`max_values`: None, `max_size`: Some(46), added: 2521, mode: `MaxEncodedLen`)
	/// Storage: `NftCredits::AwardedNftClaimCredits` (r:1 w:1)
	/// Proof: `NftCredits::AwardedNftClaimCredits` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	/// Storage: `NftCredits::CreditBufferCursor` (r:1 w:1)
	/// Proof: `NftCredits::CreditBufferCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NftCredits::CreditBuffers` (r:1 w:1)
	/// Proof: `NftCredits::CreditBuffers` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `NftCredits::NftClaimCreditAwards` (r:3 w:3)
	/// Proof: `NftCredits::NftClaimCreditAwards` (`max_values`: None, `max_size`: Some(2105), added: 4580, mode: `MaxEncodedLen`)
	/// Storage: `NftCredits::NftClaimCreditBlocks` (r:1 w:1)
	/// Proof: `NftCredits::NftClaimCreditBlocks` (`max_values`: None, `max_size`: Some(1075), added: 3550, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(265), added: 2740, mode: `MaxEncodedLen`)
	/// Storage: `Game::Players` (r:2 w:1)
	/// Proof: `Game::Players` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 10]`.
	fn player_process_step1_inner_loop(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1910 + r * (513 ±0)`
		//  Estimated: `6100 + r * (22689 ±0)`
		// Minimum execution time: 259_740_000 picoseconds.
		Weight::from_parts(116_457_782, 0)
			.saturating_add(Weight::from_parts(0, 6100))
			// Standard Error: 143_351
			.saturating_add(Weight::from_parts(156_863_682, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(15))
			.saturating_add(T::DbWeight::get().reads((9_u64).saturating_mul(r.into())))
			.saturating_add(T::DbWeight::get().writes(11))
			.saturating_add(Weight::from_parts(0, 22689).saturating_mul(r.into()))
	}
	/// Storage: `Game::Game` (r:1 w:1)
	/// Proof: `Game::Game` (`max_values`: Some(1), `max_size`: Some(74), added: 569, mode: `MaxEncodedLen`)
	fn player_process_step2() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `279`
		//  Estimated: `1559`
		// Minimum execution time: 15_953_000 picoseconds.
		Weight::from_parts(17_074_000, 0)
			.saturating_add(Weight::from_parts(0, 1559))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Game::IndexToPlayer` (r:101 w:100)
	/// Proof: `Game::IndexToPlayer` (`max_values`: None, `max_size`: Some(46), added: 2521, mode: `MaxEncodedLen`)
	/// Storage: `Game::PlayerToIndex` (r:101 w:100)
	/// Proof: `Game::PlayerToIndex` (`max_values`: None, `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `NftCredits::AwardedNftClaimCredits` (r:101 w:100)
	/// Proof: `NftCredits::AwardedNftClaimCredits` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	fn player_process_step2_inner_loop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `21156`
		//  Estimated: `260055`
		// Minimum execution time: 303_123_000 picoseconds.
		Weight::from_parts(315_125_000, 0)
			.saturating_add(Weight::from_parts(0, 260055))
			.saturating_add(T::DbWeight::get().reads(303))
			.saturating_add(T::DbWeight::get().writes(300))
	}
	/// Storage: `Game::Game` (r:1 w:1)
	/// Proof: `Game::Game` (`max_values`: Some(1), `max_size`: Some(74), added: 569, mode: `MaxEncodedLen`)
	/// Storage: `Game::Players` (r:1 w:0)
	/// Proof: `Game::Players` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Game::GameHistory` (r:0 w:1)
	/// Proof: `Game::GameHistory` (`max_values`: None, `max_size`: Some(16), added: 2491, mode: `MaxEncodedLen`)
	fn process_cancelling() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `172`
		//  Estimated: `3545`
		// Minimum execution time: 8_738_000 picoseconds.
		Weight::from_parts(9_446_000, 0)
			.saturating_add(Weight::from_parts(0, 3545))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Game::ShuffleRecognized` (r:101 w:100)
	/// Proof: `Game::ShuffleRecognized` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Game::ShuffleNotRecognized` (r:101 w:100)
	/// Proof: `Game::ShuffleNotRecognized` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	fn process_cancelling_step_shuffle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `14190`
		//  Estimated: `258439`
		// Minimum execution time: 194_684_000 picoseconds.
		Weight::from_parts(203_379_000, 0)
			.saturating_add(Weight::from_parts(0, 258439))
			.saturating_add(T::DbWeight::get().reads(202))
			.saturating_add(T::DbWeight::get().writes(200))
	}
	/// Storage: `Game::Players` (r:2 w:1)
	/// Proof: `Game::Players` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Game::PlayerToIndex` (r:1 w:1)
	/// Proof: `Game::PlayerToIndex` (`max_values`: None, `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `NftCredits::AwardedNftClaimCredits` (r:0 w:1)
	/// Proof: `NftCredits::AwardedNftClaimCredits` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	/// Storage: `Game::IndexToPlayer` (r:0 w:10)
	/// Proof: `Game::IndexToPlayer` (`max_values`: None, `max_size`: Some(46), added: 2521, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	fn process_cancelling_step_player(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `381 + n * (4 ±0)`
		//  Estimated: `6100`
		// Minimum execution time: 19_390_000 picoseconds.
		Weight::from_parts(20_156_252, 0)
			.saturating_add(Weight::from_parts(0, 6100))
			// Standard Error: 31_358
			.saturating_add(Weight::from_parts(1_373_950, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
	}
	/// Storage: `Game::Game` (r:1 w:1)
	/// Proof: `Game::Game` (`max_values`: Some(1), `max_size`: Some(74), added: 569, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Game::StmtAccountToAlias` (r:1 w:0)
	/// Proof: `Game::StmtAccountToAlias` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Game::Players` (r:1 w:1)
	/// Proof: `Game::Players` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Game::ArchivedPlayers` (r:1 w:0)
	/// Proof: `Game::ArchivedPlayers` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `Score::Participants` (r:1 w:1)
	/// Proof: `Score::Participants` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Airdrop::Events` (r:16 w:16)
	/// Proof: `Airdrop::Events` (`max_values`: None, `max_size`: Some(800), added: 3275, mode: `MaxEncodedLen`)
	/// Storage: `Airdrop::Registrations` (r:16 w:16)
	/// Proof: `Airdrop::Registrations` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653adef12e42f3e487e9b14095` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653adef12e42f3e487e9b14095` (r:1 w:1)
	/// Storage: `Game::CommunicationIdentifiers` (r:0 w:1)
	/// Proof: `Game::CommunicationIdentifiers` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 16]`.
	fn sign_up_with_invite(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `558 + n * (178 ±0)`
		//  Estimated: `4008 + n * (3275 ±0)`
		// Minimum execution time: 47_985_000 picoseconds.
		Weight::from_parts(52_919_864, 0)
			.saturating_add(Weight::from_parts(0, 4008))
			// Standard Error: 120_425
			.saturating_add(Weight::from_parts(656_792_726, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(6))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 3275).saturating_mul(n.into()))
	}
	/// Storage: `Game::Game` (r:1 w:1)
	/// Proof: `Game::Game` (`max_values`: Some(1), `max_size`: Some(74), added: 569, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Game::StmtAccountToAlias` (r:1 w:0)
	/// Proof: `Game::StmtAccountToAlias` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Game::Players` (r:1 w:1)
	/// Proof: `Game::Players` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Game::ArchivedPlayers` (r:1 w:0)
	/// Proof: `Game::ArchivedPlayers` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `Score::Participants` (r:1 w:1)
	/// Proof: `Score::Participants` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Game::PlayDepositAmount` (r:1 w:0)
	/// Proof: `Game::PlayDepositAmount` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(265), added: 2740, mode: `MaxEncodedLen`)
	/// Storage: `Airdrop::Events` (r:16 w:16)
	/// Proof: `Airdrop::Events` (`max_values`: None, `max_size`: Some(800), added: 3275, mode: `MaxEncodedLen`)
	/// Storage: `Airdrop::Registrations` (r:16 w:16)
	/// Proof: `Airdrop::Registrations` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653adef12e42f3e487e9b14095` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653adef12e42f3e487e9b14095` (r:1 w:1)
	/// Storage: `Game::CommunicationIdentifiers` (r:0 w:1)
	/// Proof: `Game::CommunicationIdentifiers` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 16]`.
	fn sign_up_with_account_new(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `661 + n * (178 ±0)`
		//  Estimated: `4111 + n * (3275 ±0)`
		// Minimum execution time: 85_018_000 picoseconds.
		Weight::from_parts(96_879_941, 0)
			.saturating_add(Weight::from_parts(0, 4111))
			// Standard Error: 85_641
			.saturating_add(Weight::from_parts(656_151_281, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(7))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 3275).saturating_mul(n.into()))
	}
	/// Storage: `Game::Game` (r:1 w:1)
	/// Proof: `Game::Game` (`max_values`: Some(1), `max_size`: Some(74), added: 569, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Game::StmtAccountToAlias` (r:1 w:0)
	/// Proof: `Game::StmtAccountToAlias` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Game::Players` (r:1 w:1)
	/// Proof: `Game::Players` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Game::ArchivedPlayers` (r:1 w:0)
	/// Proof: `Game::ArchivedPlayers` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `Score::Participants` (r:1 w:0)
	/// Proof: `Score::Participants` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::Root` (r:1 w:0)
	/// Proof: `Members::Root` (`max_values`: None, `max_size`: Some(1192), added: 3667, mode: `MaxEncodedLen`)
	/// Storage: `Airdrop::Events` (r:16 w:16)
	/// Proof: `Airdrop::Events` (`max_values`: None, `max_size`: Some(800), added: 3275, mode: `MaxEncodedLen`)
	/// Storage: `Airdrop::Registrations` (r:16 w:16)
	/// Proof: `Airdrop::Registrations` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	/// Storage: `Game::CommunicationIdentifiers` (r:0 w:1)
	/// Proof: `Game::CommunicationIdentifiers` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 16]`.
	fn sign_up_with_account_recognized(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2126 + n * (178 ±0)`
		//  Estimated: `4657 + n * (3275 ±0)`
		// Minimum execution time: 42_046_000 picoseconds.
		Weight::from_parts(176_996_145, 0)
			.saturating_add(Weight::from_parts(0, 4657))
			// Standard Error: 2_656_721
			.saturating_add(Weight::from_parts(29_046_886_714, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(3))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 3275).saturating_mul(n.into()))
	}
	/// Storage: `NetworkSuffix::NetworkSuffix` (r:1 w:0)
	/// Proof: `NetworkSuffix::NetworkSuffix` (`max_values`: Some(1), `max_size`: Some(17), added: 512, mode: `MaxEncodedLen`)
	/// Storage: `Game::Game` (r:1 w:1)
	/// Proof: `Game::Game` (`max_values`: Some(1), `max_size`: Some(74), added: 569, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Game::AliasToStmtAccount` (r:1 w:1)
	/// Proof: `Game::AliasToStmtAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a6b79c57e6a095239282c04` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653a6b79c57e6a095239282c04` (r:1 w:1)
	/// Storage: `Game::StmtAccountToAlias` (r:1 w:2)
	/// Proof: `Game::StmtAccountToAlias` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Game::Players` (r:2 w:1)
	/// Proof: `Game::Players` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Game::ArchivedPlayers` (r:2 w:0)
	/// Proof: `Game::ArchivedPlayers` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653acecc1507dc1ddd7295951c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653acecc1507dc1ddd7295951c` (r:1 w:1)
	/// Storage: `Score::Participants` (r:1 w:1)
	/// Proof: `Score::Participants` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Score::PersonhoodThreshold` (r:1 w:0)
	/// Proof: `Score::PersonhoodThreshold` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::Root` (r:1 w:0)
	/// Proof: `Members::Root` (`max_values`: None, `max_size`: Some(1192), added: 3667, mode: `MaxEncodedLen`)
	/// Storage: `Airdrop::Events` (r:16 w:16)
	/// Proof: `Airdrop::Events` (`max_values`: None, `max_size`: Some(800), added: 3275, mode: `MaxEncodedLen`)
	/// Storage: `Airdrop::Registrations` (r:16 w:16)
	/// Proof: `Airdrop::Registrations` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	/// Storage: `Game::CommunicationIdentifiers` (r:0 w:1)
	/// Proof: `Game::CommunicationIdentifiers` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 16]`.
	fn sign_up_with_alias(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2203 + n * (178 ±0)`
		//  Estimated: `6100 + n * (3275 ±8)`
		// Minimum execution time: 111_970_000 picoseconds.
		Weight::from_parts(258_659_069, 0)
			.saturating_add(Weight::from_parts(0, 6100))
			// Standard Error: 2_488_798
			.saturating_add(Weight::from_parts(29_055_573_940, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(15))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(9))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 3275).saturating_mul(n.into()))
	}
	/// Storage: `NetworkSuffix::NetworkSuffix` (r:1 w:0)
	/// Proof: `NetworkSuffix::NetworkSuffix` (`max_values`: Some(1), `max_size`: Some(17), added: 512, mode: `MaxEncodedLen`)
	/// Storage: `Game::LiteInvites` (r:1 w:1)
	/// Proof: `Game::LiteInvites` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Game::Game` (r:1 w:1)
	/// Proof: `Game::Game` (`max_values`: Some(1), `max_size`: Some(74), added: 569, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Game::StmtAccountToAlias` (r:1 w:0)
	/// Proof: `Game::StmtAccountToAlias` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Game::Players` (r:1 w:1)
	/// Proof: `Game::Players` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Game::ArchivedPlayers` (r:1 w:0)
	/// Proof: `Game::ArchivedPlayers` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `Score::Participants` (r:1 w:1)
	/// Proof: `Score::Participants` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Airdrop::Events` (r:16 w:16)
	/// Proof: `Airdrop::Events` (`max_values`: None, `max_size`: Some(800), added: 3275, mode: `MaxEncodedLen`)
	/// Storage: `Airdrop::Registrations` (r:16 w:16)
	/// Proof: `Airdrop::Registrations` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653adef12e42f3e487e9b14095` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653adef12e42f3e487e9b14095` (r:1 w:1)
	/// Storage: `Game::CommunicationIdentifiers` (r:0 w:1)
	/// Proof: `Game::CommunicationIdentifiers` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 16]`.
	fn sign_up_with_account_lite_invite(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `735 + n * (178 ±0)`
		//  Estimated: `4185 + n * (3275 ±0)`
		// Minimum execution time: 60_092_000 picoseconds.
		Weight::from_parts(71_560_066, 0)
			.saturating_add(Weight::from_parts(0, 4185))
			// Standard Error: 70_150
			.saturating_add(Weight::from_parts(654_285_895, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(7))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 3275).saturating_mul(n.into()))
	}
	/// Storage: `NetworkSuffix::NetworkSuffix` (r:1 w:0)
	/// Proof: `NetworkSuffix::NetworkSuffix` (`max_values`: Some(1), `max_size`: Some(17), added: 512, mode: `MaxEncodedLen`)
	/// Storage: `Game::Game` (r:1 w:1)
	/// Proof: `Game::Game` (`max_values`: Some(1), `max_size`: Some(74), added: 569, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NftCredits::CreditBufferCursor` (r:1 w:1)
	/// Proof: `NftCredits::CreditBufferCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NftCredits::CreditBuffers` (r:1 w:1)
	/// Proof: `NftCredits::CreditBuffers` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `Game::Players` (r:91 w:91)
	/// Proof: `Game::Players` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Game::PlayerToIndex` (r:1 w:0)
	/// Proof: `Game::PlayerToIndex` (`max_values`: None, `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `Game::IndexToPlayer` (r:90 w:0)
	/// Proof: `Game::IndexToPlayer` (`max_values`: None, `max_size`: Some(46), added: 2521, mode: `MaxEncodedLen`)
	/// Storage: `NftCredits::AwardedNftClaimCredits` (r:90 w:90)
	/// Proof: `NftCredits::AwardedNftClaimCredits` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	/// Storage: `NftCredits::NftClaimCreditAwards` (r:3 w:3)
	/// Proof: `NftCredits::NftClaimCreditAwards` (`max_values`: None, `max_size`: Some(2105), added: 4580, mode: `MaxEncodedLen`)
	/// Storage: `NftCredits::NftClaimCreditBlocks` (r:90 w:90)
	/// Proof: `NftCredits::NftClaimCreditBlocks` (`max_values`: None, `max_size`: Some(1075), added: 3550, mode: `MaxEncodedLen`)
	/// Storage: `Score::Participants` (r:9 w:9)
	/// Proof: `Score::Participants` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Score::PersonhoodThreshold` (r:1 w:0)
	/// Proof: `Score::PersonhoodThreshold` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Score::AbsenceGraceRatio` (r:1 w:0)
	/// Proof: `Score::AbsenceGraceRatio` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `Game::PlayerAttendanceHistory` (r:9 w:9)
	/// Proof: `Game::PlayerAttendanceHistory` (`max_values`: None, `max_size`: Some(98), added: 2573, mode: `MaxEncodedLen`)
	/// Storage: `Game::GameParticipantCount` (r:1 w:1)
	/// Proof: `Game::GameParticipantCount` (`max_values`: None, `max_size`: Some(16), added: 2491, mode: `MaxEncodedLen`)
	/// The range of component `e` is `[9, 90]`.
	/// The range of component `n` is `[0, 9]`.
	fn report(e: u32, n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6397 + e * (252 ±0) + n * (233 ±0)`
		//  Estimated: `8337 + e * (3439 ±5) + n * (2573 ±48)`
		// Minimum execution time: 540_119_000 picoseconds.
		Weight::from_parts(182_722_033, 0)
			.saturating_add(Weight::from_parts(0, 8337))
			// Standard Error: 91_939
			.saturating_add(Weight::from_parts(30_220_021, 0).saturating_mul(e.into()))
			// Standard Error: 784_330
			.saturating_add(Weight::from_parts(27_048_764, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(17))
			.saturating_add(T::DbWeight::get().reads((4_u64).saturating_mul(e.into())))
			.saturating_add(T::DbWeight::get().reads((4_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(10))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(e.into())))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 3439).saturating_mul(e.into()))
			.saturating_add(Weight::from_parts(0, 2573).saturating_mul(n.into()))
	}
	/// Storage: `NetworkSuffix::NetworkSuffix` (r:1 w:0)
	/// Proof: `NetworkSuffix::NetworkSuffix` (`max_values`: Some(1), `max_size`: Some(17), added: 512, mode: `MaxEncodedLen`)
	/// Storage: `Game::ArchivedPlayers` (r:1 w:0)
	/// Proof: `Game::ArchivedPlayers` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `Game::Players` (r:1 w:1)
	/// Proof: `Game::Players` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Game::Game` (r:1 w:0)
	/// Proof: `Game::Game` (`max_values`: Some(1), `max_size`: Some(74), added: 569, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(265), added: 2740, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ad861ea1ebf4800d4b89f4f` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653ad861ea1ebf4800d4b89f4f` (r:1 w:1)
	/// Storage: `Score::Participants` (r:1 w:1)
	/// Proof: `Score::Participants` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingsState` (r:1 w:1)
	/// Proof: `Members::RingsState` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `People::People` (r:1 w:1)
	/// Proof: `People::People` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `Members::Members` (r:1 w:1)
	/// Proof: `Members::Members` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `Members::OnboardingQueue` (r:1 w:1)
	/// Proof: `Members::OnboardingQueue` (`max_values`: None, `max_size`: Some(8206), added: 10681, mode: `MaxEncodedLen`)
	fn offboard_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1336`
		//  Estimated: `11671`
		// Minimum execution time: 120_146_000 picoseconds.
		Weight::from_parts(124_787_000, 0)
			.saturating_add(Weight::from_parts(0, 11671))
			.saturating_add(T::DbWeight::get().reads(12))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `NetworkSuffix::NetworkSuffix` (r:1 w:0)
	/// Proof: `NetworkSuffix::NetworkSuffix` (`max_values`: Some(1), `max_size`: Some(17), added: 512, mode: `MaxEncodedLen`)
	/// Storage: `Game::ArchivedPlayers` (r:1 w:1)
	/// Proof: `Game::ArchivedPlayers` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `Game::Players` (r:1 w:1)
	/// Proof: `Game::Players` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Game::Game` (r:1 w:0)
	/// Proof: `Game::Game` (`max_values`: Some(1), `max_size`: Some(74), added: 569, mode: `MaxEncodedLen`)
	/// Storage: `Game::AliasToStmtAccount` (r:1 w:1)
	/// Proof: `Game::AliasToStmtAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653acecc1507dc1ddd7295951c` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x3a73746174656d656e745f616c6c6f77616e63653acecc1507dc1ddd7295951c` (r:1 w:1)
	/// Storage: `Score::Participants` (r:1 w:1)
	/// Proof: `Score::Participants` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Game::StmtAccountToAlias` (r:0 w:1)
	/// Proof: `Game::StmtAccountToAlias` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn offboard_person() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `823`
		//  Estimated: `4288`
		// Minimum execution time: 46_635_000 picoseconds.
		Weight::from_parts(49_563_000, 0)
			.saturating_add(Weight::from_parts(0, 4288))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `Game::ArchivedPlayers` (r:1 w:1)
	/// Proof: `Game::ArchivedPlayers` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `Score::Participants` (r:1 w:1)
	/// Proof: `Score::Participants` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingsState` (r:1 w:1)
	/// Proof: `Members::RingsState` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `People::People` (r:1 w:1)
	/// Proof: `People::People` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `Members::Members` (r:1 w:1)
	/// Proof: `Members::Members` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `Members::OnboardingQueue` (r:1 w:1)
	/// Proof: `Members::OnboardingQueue` (`max_values`: None, `max_size`: Some(8206), added: 10681, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn kickout() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1292`
		//  Estimated: `11671`
		// Minimum execution time: 76_181_000 picoseconds.
		Weight::from_parts(79_973_000, 0)
			.saturating_add(Weight::from_parts(0, 11671))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `Game::AvailableInvites` (r:1 w:1)
	/// Proof: `Game::AvailableInvites` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn grant_invites() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `3517`
		// Minimum execution time: 10_684_000 picoseconds.
		Weight::from_parts(11_416_000, 0)
			.saturating_add(Weight::from_parts(0, 3517))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Game::PendingInvites` (r:10000 w:10000)
	/// Proof: `Game::PendingInvites` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `Game::AvailableInvites` (r:0 w:1)
	/// Proof: `Game::AvailableInvites` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10000]`.
	fn remove_available_and_pending_invites(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `763 + n * (52 ±0)`
		//  Estimated: `990 + n * (2571 ±0)`
		// Minimum execution time: 12_673_000 picoseconds.
		Weight::from_parts(13_194_000, 0)
			.saturating_add(Weight::from_parts(0, 990))
			// Standard Error: 5_634
			.saturating_add(Weight::from_parts(1_988_882, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2571).saturating_mul(n.into()))
	}
	/// Storage: `Game::AvailableInvites` (r:1 w:1)
	/// Proof: `Game::AvailableInvites` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Game::PendingInvites` (r:1 w:1)
	/// Proof: `Game::PendingInvites` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	fn set_invite_ticket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `187`
		//  Estimated: `3561`
		// Minimum execution time: 17_746_000 picoseconds.
		Weight::from_parts(18_944_000, 0)
			.saturating_add(Weight::from_parts(0, 3561))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Game::PendingInvites` (r:1 w:1)
	/// Proof: `Game::PendingInvites` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `Game::AvailableInvites` (r:1 w:1)
	/// Proof: `Game::AvailableInvites` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn cancel_invite_ticket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `231`
		//  Estimated: `3561`
		// Minimum execution time: 16_564_000 picoseconds.
		Weight::from_parts(17_702_000, 0)
			.saturating_add(Weight::from_parts(0, 3561))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Game::GameSchedules` (r:1 w:1)
	/// Proof: `Game::GameSchedules` (`max_values`: Some(1), `max_size`: Some(121849), added: 122344, mode: `MaxEncodedLen`)
	/// Storage: `Game::Game` (r:1 w:0)
	/// Proof: `Game::Game` (`max_values`: Some(1), `max_size`: Some(74), added: 569, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Game::StoredPhaseDurations` (r:1 w:0)
	/// Proof: `Game::StoredPhaseDurations` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 12]`.
	fn schedule_games(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `324`
		//  Estimated: `123334`
		// Minimum execution time: 32_879_000 picoseconds.
		Weight::from_parts(25_733_321, 0)
			.saturating_add(Weight::from_parts(0, 123334))
			// Standard Error: 12_646
			.saturating_add(Weight::from_parts(8_508_101, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Game::GameSchedules` (r:1 w:1)
	/// Proof: `Game::GameSchedules` (`max_values`: Some(1), `max_size`: Some(121849), added: 122344, mode: `MaxEncodedLen`)
	fn remove_scheduled_game() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `8705`
		//  Estimated: `123334`
		// Minimum execution time: 178_856_000 picoseconds.
		Weight::from_parts(185_213_000, 0)
			.saturating_add(Weight::from_parts(0, 123334))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Game::PlayDepositAmount` (r:0 w:1)
	/// Proof: `Game::PlayDepositAmount` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn set_play_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_568_000 picoseconds.
		Weight::from_parts(6_063_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Game::Players` (r:1 w:0)
	/// Proof: `Game::Players` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Game::Game` (r:1 w:0)
	/// Proof: `Game::Game` (`max_values`: Some(1), `max_size`: Some(74), added: 569, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Game::StmtAccountToAlias` (r:1 w:0)
	/// Proof: `Game::StmtAccountToAlias` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Game::ArchivedPlayers` (r:1 w:0)
	/// Proof: `Game::ArchivedPlayers` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `Score::Participants` (r:1 w:0)
	/// Proof: `Score::Participants` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Game::PendingInvites` (r:1 w:1)
	/// Proof: `Game::PendingInvites` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Airdrop::Events` (r:16 w:0)
	/// Proof: `Airdrop::Events` (`max_values`: None, `max_size`: Some(800), added: 3275, mode: `MaxEncodedLen`)
	/// Storage: `Airdrop::Registrations` (r:16 w:0)
	/// Proof: `Airdrop::Registrations` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 16]`.
	fn as_invited_tx_ext(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `677 + n * (178 ±0)`
		//  Estimated: `3593 + n * (3275 ±0)`
		// Minimum execution time: 94_073_000 picoseconds.
		Weight::from_parts(157_757_576, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			// Standard Error: 264_084
			.saturating_add(Weight::from_parts(658_292_982, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(Weight::from_parts(0, 3275).saturating_mul(n.into()))
	}
	/// Storage: `Game::GameIndex` (r:1 w:0)
	/// Proof: `Game::GameIndex` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Game::Game` (r:1 w:1)
	/// Proof: `Game::Game` (`max_values`: Some(1), `max_size`: Some(74), added: 569, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn end_reporting() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `264`
		//  Estimated: `1559`
		// Minimum execution time: 13_089_000 picoseconds.
		Weight::from_parts(14_086_000, 0)
			.saturating_add(Weight::from_parts(0, 1559))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Game::PlayerAttendanceHistory` (r:1 w:1)
	/// Proof: `Game::PlayerAttendanceHistory` (`max_values`: None, `max_size`: Some(98), added: 2573, mode: `MaxEncodedLen`)
	/// Storage: `Game::GameParticipantCount` (r:1 w:1)
	/// Proof: `Game::GameParticipantCount` (`max_values`: None, `max_size`: Some(16), added: 2491, mode: `MaxEncodedLen`)
	fn insert_attendance_history() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `235`
		//  Estimated: `3563`
		// Minimum execution time: 9_483_000 picoseconds.
		Weight::from_parts(10_373_000, 0)
			.saturating_add(Weight::from_parts(0, 3563))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Game::Game` (r:1 w:1)
	/// Proof: `Game::Game` (`max_values`: Some(1), `max_size`: Some(74), added: 569, mode: `MaxEncodedLen`)
	/// Storage: `Airdrop::Events` (r:16 w:16)
	/// Proof: `Airdrop::Events` (`max_values`: None, `max_size`: Some(800), added: 3275, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::Holds` (r:1 w:1)
	/// Proof: `AssetsHolder::Holds` (`max_values`: None, `max_size`: Some(883), added: 3358, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:1)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(682), added: 3157, mode: `MaxEncodedLen`)
	/// Storage: `Airdrop::ActionSchedule` (r:0 w:32)
	/// Proof: `Airdrop::ActionSchedule` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	fn cancel_game() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3939`
		//  Estimated: `53390`
		// Minimum execution time: 1_169_553_000 picoseconds.
		Weight::from_parts(1_206_708_000, 0)
			.saturating_add(Weight::from_parts(0, 53390))
			.saturating_add(T::DbWeight::get().reads(22))
			.saturating_add(T::DbWeight::get().writes(54))
	}
	/// Storage: `Game::Game` (r:1 w:0)
	/// Proof: `Game::Game` (`max_values`: Some(1), `max_size`: Some(74), added: 569, mode: `MaxEncodedLen`)
	/// Storage: `Game::StoredPhaseDurations` (r:0 w:1)
	/// Proof: `Game::StoredPhaseDurations` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	fn set_game_phases() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `230`
		//  Estimated: `1559`
		// Minimum execution time: 12_704_000 picoseconds.
		Weight::from_parts(13_716_000, 0)
			.saturating_add(Weight::from_parts(0, 1559))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Airdrop::Events` (r:16 w:16)
	/// Proof: `Airdrop::Events` (`max_values`: None, `max_size`: Some(800), added: 3275, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::Holds` (r:1 w:1)
	/// Proof: `AssetsHolder::Holds` (`max_values`: None, `max_size`: Some(883), added: 3358, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:1)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(682), added: 3157, mode: `MaxEncodedLen`)
	/// Storage: `Airdrop::ActionSchedule` (r:0 w:16)
	/// Proof: `Airdrop::ActionSchedule` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 16]`.
	fn on_game_cancelled(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `851 + n * (174 ±0)`
		//  Estimated: `7404 + n * (3275 ±0)`
		// Minimum execution time: 3_146_000 picoseconds.
		Weight::from_parts(25_772_798, 0)
			.saturating_add(Weight::from_parts(0, 7404))
			// Standard Error: 91_043
			.saturating_add(Weight::from_parts(70_403_354, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 3275).saturating_mul(n.into()))
	}
	/// Storage: `NetworkSuffix::NetworkSuffix` (r:1 w:0)
	/// Proof: `NetworkSuffix::NetworkSuffix` (`max_values`: Some(1), `max_size`: Some(17), added: 512, mode: `MaxEncodedLen`)
	/// Storage: `Score::Participants` (r:1 w:0)
	/// Proof: `Score::Participants` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Airdrop::Events` (r:1 w:1)
	/// Proof: `Airdrop::Events` (`max_values`: None, `max_size`: Some(800), added: 3275, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Airdrop::SupportedAssets` (r:1 w:0)
	/// Proof: `Airdrop::SupportedAssets` (`max_values`: None, `max_size`: Some(626), added: 3101, mode: `MaxEncodedLen`)
	/// Storage: `Airdrop::Winners` (r:1 w:1)
	/// Proof: `Airdrop::Winners` (`max_values`: None, `max_size`: Some(121), added: 2596, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::Holds` (r:1 w:1)
	/// Proof: `AssetsHolder::Holds` (`max_values`: None, `max_size`: Some(883), added: 3358, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:1)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(682), added: 3157, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim_airdrop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1538`
		//  Estimated: `7404`
		// Minimum execution time: 135_558_000 picoseconds.
		Weight::from_parts(141_742_000, 0)
			.saturating_add(Weight::from_parts(0, 7404))
			.saturating_add(T::DbWeight::get().reads(12))
			.saturating_add(T::DbWeight::get().writes(8))
	}
}
