// Copyright (C) Parity Technologies (UK) Ltd.
// This file is part of Individuality.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `indiv_pallet_members_subscriber`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 60.0.0
//! DATE: 2026-10-08, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `parity-weights-a11366e5c2da5f36`, CPU: `Intel(R) Xeon(R) CPU @ 2.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --extrinsic=*
// --runtime=target/production/wbuild/next-asset-hub-paseo-runtime/next_asset_hub_paseo_runtime.wasm
// --pallet=indiv_pallet_members_subscriber
// --header=/home/runner/actions-runner/_work/individuality-community/individuality-community/.github/scripts/cmd/file_header.txt
// --output=./runtimes/next-asset-hub-paseo/src/weights
// --wasm-execution=compiled
// --steps=50
// --repeat=20
// --min-duration=1
// --heap-pages=4096
// --genesis-builder=runtime
// --no-storage-info
// --no-min-squares
// --no-median-slopes

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `indiv_pallet_members_subscriber`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> indiv_pallet_members_subscriber::WeightInfo for WeightInfo<T> {
	/// Storage: `MembersSubscriber::Subscription` (r:1 w:1)
	/// Proof: `MembersSubscriber::Subscription` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::RingCollectionExponents` (r:11 w:1)
	/// Proof: `MembersSubscriber::RingCollectionExponents` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::CurrentGeneration` (r:1 w:0)
	/// Proof: `MembersSubscriber::CurrentGeneration` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::RingCollectionStates` (r:1 w:1)
	/// Proof: `MembersSubscriber::RingCollectionStates` (`max_values`: None, `max_size`: Some(2512), added: 4987, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::RingRoots` (r:10 w:10)
	/// Proof: `MembersSubscriber::RingRoots` (`max_values`: None, `max_size`: Some(1005), added: 3480, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::ProcessingState` (r:1 w:1)
	/// Proof: `MembersSubscriber::ProcessingState` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	fn initialize_ring_roots(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `617`
		//  Estimated: `28754 + n * (3480 ±0)`
		// Minimum execution time: 1_261_580_000 picoseconds.
		Weight::from_parts(91_948_072, 0)
			.saturating_add(Weight::from_parts(0, 28754))
			// Standard Error: 193_200
			.saturating_add(Weight::from_parts(1_201_004_692, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 3480).saturating_mul(n.into()))
	}
	/// Storage: `MembersSubscriber::Subscription` (r:1 w:0)
	/// Proof: `MembersSubscriber::Subscription` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::ProcessingState` (r:1 w:1)
	/// Proof: `MembersSubscriber::ProcessingState` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::RingCollectionExponents` (r:1 w:0)
	/// Proof: `MembersSubscriber::RingCollectionExponents` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::CurrentGeneration` (r:1 w:0)
	/// Proof: `MembersSubscriber::CurrentGeneration` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::RingCollectionStates` (r:1 w:1)
	/// Proof: `MembersSubscriber::RingCollectionStates` (`max_values`: None, `max_size`: Some(2512), added: 4987, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::RingRoots` (r:10 w:10)
	/// Proof: `MembersSubscriber::RingRoots` (`max_values`: None, `max_size`: Some(1005), added: 3480, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	fn process_ring_updates(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2837 + n * (953 ±0)`
		//  Estimated: `5977 + n * (3480 ±0)`
		// Minimum execution time: 1_296_798_000 picoseconds.
		Weight::from_parts(108_136_109, 0)
			.saturating_add(Weight::from_parts(0, 5977))
			// Standard Error: 179_171
			.saturating_add(Weight::from_parts(1_214_567_155, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 3480).saturating_mul(n.into()))
	}
	/// Storage: `MembersSubscriber::Subscription` (r:1 w:0)
	/// Proof: `MembersSubscriber::Subscription` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::ProcessingState` (r:1 w:0)
	/// Proof: `MembersSubscriber::ProcessingState` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn process_ring_updates_stale_batch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `73`
		//  Estimated: `1501`
		// Minimum execution time: 7_616_000 picoseconds.
		Weight::from_parts(8_323_000, 0)
			.saturating_add(Weight::from_parts(0, 1501))
			.saturating_add(T::DbWeight::get().reads(2))
	}
	/// Storage: `MembersSubscriber::Subscription` (r:1 w:1)
	/// Proof: `MembersSubscriber::Subscription` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// Storage: `XcmpQueue::DeliveryFeeFactor` (r:1 w:0)
	/// Proof: `XcmpQueue::DeliveryFeeFactor` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `PolkadotXcm::SupportedVersion` (r:1 w:0)
	/// Proof: `PolkadotXcm::SupportedVersion` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `XcmpQueue::OutboundXcmpStatus` (r:1 w:1)
	/// Proof: `XcmpQueue::OutboundXcmpStatus` (`max_values`: Some(1), `max_size`: Some(2306), added: 2801, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::RelevantMessagingState` (r:1 w:0)
	/// Proof: `ParachainSystem::RelevantMessagingState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `MembersSubscriber::CurrentGeneration` (r:1 w:1)
	/// Proof: `MembersSubscriber::CurrentGeneration` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::QueuedRingPurge` (r:1 w:1)
	/// Proof: `MembersSubscriber::QueuedRingPurge` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::RingCollectionStates` (r:10 w:10)
	/// Proof: `MembersSubscriber::RingCollectionStates` (`max_values`: None, `max_size`: Some(2512), added: 4987, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::RingCollectionExponents` (r:10 w:10)
	/// Proof: `MembersSubscriber::RingCollectionExponents` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `XcmpQueue::OutboundXcmpMessages` (r:0 w:1)
	/// Proof: `XcmpQueue::OutboundXcmpMessages` (`max_values`: None, `max_size`: Some(105506), added: 107981, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::ProcessingState` (r:0 w:1)
	/// Proof: `MembersSubscriber::ProcessingState` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn terminate_subscription() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1779`
		//  Estimated: `50860`
		// Minimum execution time: 132_126_000 picoseconds.
		Weight::from_parts(143_076_000, 0)
			.saturating_add(Weight::from_parts(0, 50860))
			.saturating_add(T::DbWeight::get().reads(27))
			.saturating_add(T::DbWeight::get().writes(26))
	}
	/// Storage: `MembersSubscriber::CurrentGeneration` (r:1 w:1)
	/// Proof: `MembersSubscriber::CurrentGeneration` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::QueuedRingPurge` (r:1 w:1)
	/// Proof: `MembersSubscriber::QueuedRingPurge` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::RingCollectionStates` (r:10 w:10)
	/// Proof: `MembersSubscriber::RingCollectionStates` (`max_values`: None, `max_size`: Some(2512), added: 4987, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::RingCollectionExponents` (r:10 w:10)
	/// Proof: `MembersSubscriber::RingCollectionExponents` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::ProcessingState` (r:0 w:1)
	/// Proof: `MembersSubscriber::ProcessingState` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn clear_ring_data() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1484`
		//  Estimated: `50860`
		// Minimum execution time: 29_995_000 picoseconds.
		Weight::from_parts(31_886_000, 0)
			.saturating_add(Weight::from_parts(0, 50860))
			.saturating_add(T::DbWeight::get().reads(22))
			.saturating_add(T::DbWeight::get().writes(23))
	}
	/// Storage: `MembersSubscriber::QueuedRingPurge` (r:1 w:1)
	/// Proof: `MembersSubscriber::QueuedRingPurge` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::RingRoots` (r:100 w:100)
	/// Proof: `MembersSubscriber::RingRoots` (`max_values`: None, `max_size`: Some(1005), added: 3480, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::CurrentGeneration` (r:1 w:0)
	/// Proof: `MembersSubscriber::CurrentGeneration` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 100]`.
	fn purge_stale_ring_roots(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `146 + n * (56 ±0)`
		//  Estimated: `1493 + n * (3480 ±0)`
		// Minimum execution time: 19_838_000 picoseconds.
		Weight::from_parts(35_039_058, 0)
			.saturating_add(Weight::from_parts(0, 1493))
			// Standard Error: 12_531
			.saturating_add(Weight::from_parts(1_556_818, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 3480).saturating_mul(n.into()))
	}
	/// Storage: `MembersSubscriber::QueuedRingPurge` (r:1 w:0)
	/// Proof: `MembersSubscriber::QueuedRingPurge` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::CurrentGeneration` (r:1 w:0)
	/// Proof: `MembersSubscriber::CurrentGeneration` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn authorize_purge_stale_ring_roots() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `59`
		//  Estimated: `1493`
		// Minimum execution time: 5_523_000 picoseconds.
		Weight::from_parts(6_003_000, 0)
			.saturating_add(Weight::from_parts(0, 1493))
			.saturating_add(T::DbWeight::get().reads(2))
	}
	/// Storage: `MembersSubscriber::RingCollectionStates` (r:1 w:1)
	/// Proof: `MembersSubscriber::RingCollectionStates` (`max_values`: None, `max_size`: Some(2512), added: 4987, mode: `MaxEncodedLen`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `XcmpQueue::DeliveryFeeFactor` (r:1 w:0)
	/// Proof: `XcmpQueue::DeliveryFeeFactor` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `PolkadotXcm::SupportedVersion` (r:1 w:0)
	/// Proof: `PolkadotXcm::SupportedVersion` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `XcmpQueue::OutboundXcmpStatus` (r:1 w:1)
	/// Proof: `XcmpQueue::OutboundXcmpStatus` (`max_values`: Some(1), `max_size`: Some(2306), added: 2801, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::RelevantMessagingState` (r:1 w:0)
	/// Proof: `ParachainSystem::RelevantMessagingState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `MembersSubscriber::ProcessingState` (r:1 w:1)
	/// Proof: `MembersSubscriber::ProcessingState` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `XcmpQueue::OutboundXcmpMessages` (r:0 w:1)
	/// Proof: `XcmpQueue::OutboundXcmpMessages` (`max_values`: None, `max_size`: Some(105506), added: 107981, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 255]`.
	fn replay_missing_roots(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `574 + n * (8 ±0)`
		//  Estimated: `5977 + n * (8 ±0)`
		// Minimum execution time: 55_469_000 picoseconds.
		Weight::from_parts(49_813_391, 0)
			.saturating_add(Weight::from_parts(0, 5977))
			// Standard Error: 3_135
			.saturating_add(Weight::from_parts(2_233_681, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(Weight::from_parts(0, 8).saturating_mul(n.into()))
	}
	/// Storage: `MembersSubscriber::Subscription` (r:1 w:0)
	/// Proof: `MembersSubscriber::Subscription` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::ProcessingState` (r:1 w:0)
	/// Proof: `MembersSubscriber::ProcessingState` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::RingCollectionStates` (r:1 w:0)
	/// Proof: `MembersSubscriber::RingCollectionStates` (`max_values`: None, `max_size`: Some(2512), added: 4987, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 255]`.
	fn authorize_replay_missing_roots(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `207 + n * (8 ±0)`
		//  Estimated: `5977`
		// Minimum execution time: 15_394_000 picoseconds.
		Weight::from_parts(16_855_745, 0)
			.saturating_add(Weight::from_parts(0, 5977))
			// Standard Error: 173
			.saturating_add(Weight::from_parts(47_926, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(4))
	}
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `XcmpQueue::DeliveryFeeFactor` (r:1 w:0)
	/// Proof: `XcmpQueue::DeliveryFeeFactor` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `PolkadotXcm::SupportedVersion` (r:1 w:0)
	/// Proof: `PolkadotXcm::SupportedVersion` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `XcmpQueue::OutboundXcmpStatus` (r:1 w:1)
	/// Proof: `XcmpQueue::OutboundXcmpStatus` (`max_values`: Some(1), `max_size`: Some(2306), added: 2801, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::RelevantMessagingState` (r:1 w:0)
	/// Proof: `ParachainSystem::RelevantMessagingState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `XcmpQueue::OutboundXcmpMessages` (r:0 w:1)
	/// Proof: `XcmpQueue::OutboundXcmpMessages` (`max_values`: None, `max_size`: Some(105506), added: 107981, mode: `MaxEncodedLen`)
	fn send_replay_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `367`
		//  Estimated: `3832`
		// Minimum execution time: 30_401_000 picoseconds.
		Weight::from_parts(32_434_000, 0)
			.saturating_add(Weight::from_parts(0, 3832))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `MembersSubscriber::RingCollectionStates` (r:1 w:1)
	/// Proof: `MembersSubscriber::RingCollectionStates` (`max_values`: None, `max_size`: Some(2512), added: 4987, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::CurrentGeneration` (r:1 w:0)
	/// Proof: `MembersSubscriber::CurrentGeneration` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::RingRoots` (r:32 w:0)
	/// Proof: `MembersSubscriber::RingRoots` (`max_values`: None, `max_size`: Some(1005), added: 3480, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 32]`.
	fn detect_missing_rings(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `5093 + n * (84 ±0)`
		//  Estimated: `5977 + n * (3480 ±0)`
		// Minimum execution time: 75_163_000 picoseconds.
		Weight::from_parts(84_162_169, 0)
			.saturating_add(Weight::from_parts(0, 5977))
			// Standard Error: 26_819
			.saturating_add(Weight::from_parts(6_174_675, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(Weight::from_parts(0, 3480).saturating_mul(n.into()))
	}
	/// Storage: `MembersSubscriber::Subscription` (r:1 w:0)
	/// Proof: `MembersSubscriber::Subscription` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::RingCollectionStates` (r:1 w:0)
	/// Proof: `MembersSubscriber::RingCollectionStates` (`max_values`: None, `max_size`: Some(2512), added: 4987, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn authorize_detect_missing_rings() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2669`
		//  Estimated: `5977`
		// Minimum execution time: 39_797_000 picoseconds.
		Weight::from_parts(42_890_000, 0)
			.saturating_add(Weight::from_parts(0, 5977))
			.saturating_add(T::DbWeight::get().reads(3))
	}
}
