// Copyright (C) Parity Technologies (UK) Ltd.
// This file is part of Individuality.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_psm`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-09-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `parity-weights-4b14baff60033fd8`, CPU: `Intel(R) Xeon(R) CPU @ 2.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --extrinsic=*
// --runtime=target/production/wbuild/next-asset-hub-paseo-runtime/next_asset_hub_paseo_runtime.wasm
// --pallet=pallet_psm
// --header=/home/runner/actions-runner/_work/individuality-community/individuality-community/.github/scripts/cmd/file_header.txt
// --output=./runtimes/next-asset-hub-paseo/src/weights
// --wasm-execution=compiled
// --steps=50
// --repeat=20
// --min-duration=1
// --heap-pages=4096
// --genesis-builder=runtime
// --no-storage-info
// --no-min-squares
// --no-median-slopes

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_psm`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_psm::WeightInfo for WeightInfo<T> {
	/// Storage: `Psm::Psm` (r:1 w:0)
	/// Proof: `Psm::Psm` (`max_values`: None, `max_size`: Some(687), added: 3162, mode: `MaxEncodedLen`)
	/// Storage: `Psm::ExternalAssets` (r:1 w:0)
	/// Proof: `Psm::ExternalAssets` (`max_values`: None, `max_size`: Some(1238), added: 3713, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:2 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `Psm::MintingFee` (r:1 w:0)
	/// Proof: `Psm::MintingFee` (`max_values`: None, `max_size`: Some(1240), added: 3715, mode: `MaxEncodedLen`)
	/// Storage: `Psm::PsmDebt` (r:6 w:1)
	/// Proof: `Psm::PsmDebt` (`max_values`: None, `max_size`: Some(1252), added: 3727, mode: `MaxEncodedLen`)
	/// Storage: `Psm::AssetCeilingWeight` (r:6 w:0)
	/// Proof: `Psm::AssetCeilingWeight` (`max_values`: None, `max_size`: Some(1240), added: 3715, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:0)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:1 w:0)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 5]`.
	fn mint(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2406 + n * (105 ±0)`
		//  Estimated: `8817 + n * (3727 ±0)`
		// Minimum execution time: 170_550_000 picoseconds.
		Weight::from_parts(169_736_851, 0)
			.saturating_add(Weight::from_parts(0, 8817))
			// Standard Error: 107_736
			.saturating_add(Weight::from_parts(10_663_880, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(15))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(7))
			.saturating_add(Weight::from_parts(0, 3727).saturating_mul(n.into()))
	}
	/// Storage: `Psm::Psm` (r:1 w:0)
	/// Proof: `Psm::Psm` (`max_values`: None, `max_size`: Some(687), added: 3162, mode: `MaxEncodedLen`)
	/// Storage: `Psm::ExternalAssets` (r:1 w:0)
	/// Proof: `Psm::ExternalAssets` (`max_values`: None, `max_size`: Some(1238), added: 3713, mode: `MaxEncodedLen`)
	/// Storage: `Psm::RedemptionFee` (r:1 w:0)
	/// Proof: `Psm::RedemptionFee` (`max_values`: None, `max_size`: Some(1240), added: 3715, mode: `MaxEncodedLen`)
	/// Storage: `Psm::PsmDebt` (r:1 w:1)
	/// Proof: `Psm::PsmDebt` (`max_values`: None, `max_size`: Some(1252), added: 3727, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:2 w:0)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:2 w:0)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn redeem() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1363`
		//  Estimated: `8817`
		// Minimum execution time: 155_839_000 picoseconds.
		Weight::from_parts(164_354_000, 0)
			.saturating_add(Weight::from_parts(0, 8817))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `Psm::PsmAdmin` (r:1 w:0)
	/// Proof: `Psm::PsmAdmin` (`max_values`: None, `max_size`: Some(1875), added: 4350, mode: `MaxEncodedLen`)
	/// Storage: `Psm::ExternalAssets` (r:1 w:0)
	/// Proof: `Psm::ExternalAssets` (`max_values`: None, `max_size`: Some(1238), added: 3713, mode: `MaxEncodedLen`)
	/// Storage: `Psm::MintingFee` (r:1 w:1)
	/// Proof: `Psm::MintingFee` (`max_values`: None, `max_size`: Some(1240), added: 3715, mode: `MaxEncodedLen`)
	fn set_minting_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `317`
		//  Estimated: `5340`
		// Minimum execution time: 29_440_000 picoseconds.
		Weight::from_parts(31_171_000, 0)
			.saturating_add(Weight::from_parts(0, 5340))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Psm::PsmAdmin` (r:1 w:0)
	/// Proof: `Psm::PsmAdmin` (`max_values`: None, `max_size`: Some(1875), added: 4350, mode: `MaxEncodedLen`)
	/// Storage: `Psm::ExternalAssets` (r:1 w:0)
	/// Proof: `Psm::ExternalAssets` (`max_values`: None, `max_size`: Some(1238), added: 3713, mode: `MaxEncodedLen`)
	/// Storage: `Psm::RedemptionFee` (r:1 w:1)
	/// Proof: `Psm::RedemptionFee` (`max_values`: None, `max_size`: Some(1240), added: 3715, mode: `MaxEncodedLen`)
	fn set_redemption_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `317`
		//  Estimated: `5340`
		// Minimum execution time: 29_249_000 picoseconds.
		Weight::from_parts(31_102_000, 0)
			.saturating_add(Weight::from_parts(0, 5340))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Psm::PsmAdmin` (r:1 w:0)
	/// Proof: `Psm::PsmAdmin` (`max_values`: None, `max_size`: Some(1875), added: 4350, mode: `MaxEncodedLen`)
	/// Storage: `Psm::Psm` (r:1 w:1)
	/// Proof: `Psm::Psm` (`max_values`: None, `max_size`: Some(687), added: 3162, mode: `MaxEncodedLen`)
	fn set_max_debt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `296`
		//  Estimated: `5340`
		// Minimum execution time: 22_634_000 picoseconds.
		Weight::from_parts(24_321_000, 0)
			.saturating_add(Weight::from_parts(0, 5340))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Psm::PsmAdmin` (r:1 w:0)
	/// Proof: `Psm::PsmAdmin` (`max_values`: None, `max_size`: Some(1875), added: 4350, mode: `MaxEncodedLen`)
	/// Storage: `Psm::ExternalAssets` (r:1 w:1)
	/// Proof: `Psm::ExternalAssets` (`max_values`: None, `max_size`: Some(1238), added: 3713, mode: `MaxEncodedLen`)
	fn set_asset_status() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `317`
		//  Estimated: `5340`
		// Minimum execution time: 24_802_000 picoseconds.
		Weight::from_parts(26_369_000, 0)
			.saturating_add(Weight::from_parts(0, 5340))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Psm::PsmAdmin` (r:1 w:0)
	/// Proof: `Psm::PsmAdmin` (`max_values`: None, `max_size`: Some(1875), added: 4350, mode: `MaxEncodedLen`)
	/// Storage: `Psm::ExternalAssets` (r:1 w:0)
	/// Proof: `Psm::ExternalAssets` (`max_values`: None, `max_size`: Some(1238), added: 3713, mode: `MaxEncodedLen`)
	/// Storage: `Psm::AssetCeilingWeight` (r:1 w:1)
	/// Proof: `Psm::AssetCeilingWeight` (`max_values`: None, `max_size`: Some(1240), added: 3715, mode: `MaxEncodedLen`)
	fn set_asset_ceiling_weight() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `391`
		//  Estimated: `5340`
		// Minimum execution time: 31_616_000 picoseconds.
		Weight::from_parts(33_649_000, 0)
			.saturating_add(Weight::from_parts(0, 5340))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Psm::PsmAdmin` (r:1 w:0)
	/// Proof: `Psm::PsmAdmin` (`max_values`: None, `max_size`: Some(1875), added: 4350, mode: `MaxEncodedLen`)
	/// Storage: `Psm::Psm` (r:1 w:1)
	/// Proof: `Psm::Psm` (`max_values`: None, `max_size`: Some(687), added: 3162, mode: `MaxEncodedLen`)
	/// Storage: `Psm::ExternalAssets` (r:1 w:1)
	/// Proof: `Psm::ExternalAssets` (`max_values`: None, `max_size`: Some(1238), added: 3713, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:2 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	fn add_external_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `560`
		//  Estimated: `6220`
		// Minimum execution time: 45_322_000 picoseconds.
		Weight::from_parts(47_660_000, 0)
			.saturating_add(Weight::from_parts(0, 6220))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Psm::PsmAdmin` (r:1 w:0)
	/// Proof: `Psm::PsmAdmin` (`max_values`: None, `max_size`: Some(1875), added: 4350, mode: `MaxEncodedLen`)
	/// Storage: `Psm::Psm` (r:1 w:1)
	/// Proof: `Psm::Psm` (`max_values`: None, `max_size`: Some(687), added: 3162, mode: `MaxEncodedLen`)
	/// Storage: `Psm::ExternalAssets` (r:1 w:1)
	/// Proof: `Psm::ExternalAssets` (`max_values`: None, `max_size`: Some(1238), added: 3713, mode: `MaxEncodedLen`)
	/// Storage: `Psm::PsmDebt` (r:1 w:1)
	/// Proof: `Psm::PsmDebt` (`max_values`: None, `max_size`: Some(1252), added: 3727, mode: `MaxEncodedLen`)
	/// Storage: `Psm::AssetCeilingWeight` (r:0 w:1)
	/// Proof: `Psm::AssetCeilingWeight` (`max_values`: None, `max_size`: Some(1240), added: 3715, mode: `MaxEncodedLen`)
	/// Storage: `Psm::MintingFee` (r:0 w:1)
	/// Proof: `Psm::MintingFee` (`max_values`: None, `max_size`: Some(1240), added: 3715, mode: `MaxEncodedLen`)
	/// Storage: `Psm::RedemptionFee` (r:0 w:1)
	/// Proof: `Psm::RedemptionFee` (`max_values`: None, `max_size`: Some(1240), added: 3715, mode: `MaxEncodedLen`)
	fn remove_external_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `436`
		//  Estimated: `5340`
		// Minimum execution time: 45_220_000 picoseconds.
		Weight::from_parts(47_938_000, 0)
			.saturating_add(Weight::from_parts(0, 5340))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Psm::Psm` (r:1 w:1)
	/// Proof: `Psm::Psm` (`max_values`: None, `max_size`: Some(687), added: 3162, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(319), added: 2794, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:1 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Revive::OriginalAccount` (r:1 w:1)
	/// Proof: `Revive::OriginalAccount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Psm::PsmAdmin` (r:0 w:1)
	/// Proof: `Psm::PsmAdmin` (`max_values`: None, `max_size`: Some(1875), added: 4350, mode: `MaxEncodedLen`)
	fn create_psm() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `5299`
		//  Estimated: `4152`
		// Minimum execution time: 108_466_000 picoseconds.
		Weight::from_parts(113_406_000, 0)
			.saturating_add(Weight::from_parts(0, 4152))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `Psm::PsmAdmin` (r:1 w:1)
	/// Proof: `Psm::PsmAdmin` (`max_values`: None, `max_size`: Some(1875), added: 4350, mode: `MaxEncodedLen`)
	/// Storage: `Psm::Psm` (r:1 w:1)
	/// Proof: `Psm::Psm` (`max_values`: None, `max_size`: Some(687), added: 3162, mode: `MaxEncodedLen`)
	/// Storage: `Psm::PsmDebt` (r:1 w:0)
	/// Proof: `Psm::PsmDebt` (`max_values`: None, `max_size`: Some(1252), added: 3727, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:2 w:2)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(319), added: 2794, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Revive::OriginalAccount` (r:0 w:1)
	/// Proof: `Revive::OriginalAccount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn remove_psm() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4475`
		//  Estimated: `6578`
		// Minimum execution time: 116_059_000 picoseconds.
		Weight::from_parts(121_343_000, 0)
			.saturating_add(Weight::from_parts(0, 6578))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `Psm::PsmAdmin` (r:1 w:1)
	/// Proof: `Psm::PsmAdmin` (`max_values`: None, `max_size`: Some(1875), added: 4350, mode: `MaxEncodedLen`)
	fn set_full_admin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `214`
		//  Estimated: `5340`
		// Minimum execution time: 21_551_000 picoseconds.
		Weight::from_parts(23_256_000, 0)
			.saturating_add(Weight::from_parts(0, 5340))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Psm::PsmAdmin` (r:1 w:1)
	/// Proof: `Psm::PsmAdmin` (`max_values`: None, `max_size`: Some(1875), added: 4350, mode: `MaxEncodedLen`)
	fn set_emergency_admin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `214`
		//  Estimated: `5340`
		// Minimum execution time: 21_677_000 picoseconds.
		Weight::from_parts(23_369_000, 0)
			.saturating_add(Weight::from_parts(0, 5340))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
