name: "cargo-deny (license check)"

on:
  push:
    branches: ["main", "release-*"]
  pull_request:
  workflow_dispatch:

# cancel previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cargo-deny:
    name: Check dependency licenses
    runs-on: parity-ubuntu
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check licenses
        uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check licenses
