name: "Taplo (TOML format check)"

on:
  push:
    branches: ["main", "release-*"]
  pull_request:
  workflow_dispatch:

# cancel previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  taplo:
    name: Check TOML formatting
    runs-on: parity-ubuntu
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set env
        run: cat .github/env >> $GITHUB_ENV

      - name: Install taplo
        run: |
          curl -fsSL https://github.com/tamasfe/taplo/releases/download/${{ env.TAPLO_VERSION }}/taplo-linux-x86.gz | gunzip > taplo
          chmod +x taplo
          sudo mv taplo /usr/local/bin/

      - name: Check TOML formatting
        run: taplo format --check --diff --config ./.config/taplo.toml

